CREATE TABLE notice (
B_ID		INT NOT NULL PRIMARY KEY,
B_NAME		VARCHAR(20) NOT NULL,
B_MAIL		VARCHAR(30),
B_TITLE		VARCHAR(60) NOT NULL,
B_CONTENT	TEXT,
B_DATE		DATETIME,
B_VIEW		INT,
B_PWD		VARCHAR(12),
B_REF		INT,
B_RELEVEL	INT,
B_RESTEP	INT,
B_URL		VARCHAR(100),
B_HTML		CHAR(1),
B_FILENAME	VARCHAR(100),
B_FILESIZE	VARCHAR(20)
);
