/*
 * JSP generated by Resin-3.1.9 (built Mon, 13 Apr 2009 11:09:12 PDT)
 */

package _jsp._order;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.net.*;
import java.sql.*;
import java.text.*;
import common.util.*;
import dbconn.*;

public class _dsk_0po_0status__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;


  //-------------------------------------------
  // CopyRightLogo
  //
  //-------------------------------------------
  String CopyRightLogo()
  {
    String str;
    str = "<table width='99%' border='0' cellspacing='0' cellpadding='0' align='center'>";
    str += "<tr><td width='100%' height='2' align='center'>";
    str += "<HR width=100% size=2></td></tr>";
    str += "<tr><td width='100%' align='center'>";
    str += "<FONT size=2 >&copy;Copyright 2010 </font>";
    str += "<FONT size=2 color=green>Fast Future Brands Pty Ltd. All Rights Reserved.</FONT><BR>";
    str += "<FONT size=2> For more information,please contact</font> <FONT size=2 color=blue><A href='mailto:scm@ffb.net.au'>scm@ffb.net.au</A></FONT>";
    str += "</td></tr></table>";

    return (String)str;
  }

  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, "/error.jsp", session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
response.setHeader("Pragma","no-cache"); //HTTP 1.0
response.setDateHeader ("Expires", 0);
response.setHeader("Cache-Control","no-cache"); //HTTP 1.1

String scmid = "";
String scmnm = "";
String usertype = "";
String usergroup = "";
//String scmsubids = "";
String _adminid = "";
String _adminname = "";
String _admingroup = "";
String _apessid = "";
String _apessname = "";

try{
  scmid = (String) session.getAttribute("scmid");
  _adminid = (String) session.getAttribute("adminid");

  if( (scmid == null || scmid.length() == 0 || scmid.equals("null"))
      && (_adminid == null || _adminid.length() == 0 || _adminid.equals("null")) ) {
    response.sendRedirect("/login_first.html");
    return;
  }

  _adminname = (String) session.getAttribute("adminname");

  _apessid = (String) session.getAttribute("apessid");
  _apessname = (String) session.getAttribute("apessname");

  scmnm = (String) session.getAttribute("scmnm");

  usertype = (String) session.getAttribute("usertype");
  if (usertype == null) usertype = "";

  usergroup = (String) session.getAttribute("usergroup");
  if (usergroup == null) usergroup = "";

  //scmsubids = (String) session.getAttribute("scmsubids");
  //session.setMaxInactiveInterval(60*60);

}catch( Exception e ) {
  response.sendRedirect("/login_first.html");
  return;
}

      out.write(_jsp_string1, 0, _jsp_string1.length);
      
// Intranet DB
String _mysqlJdbcDriver = "com.mysql.jdbc.Driver";
String _urlLogin = "jdbc:mysql://10.2.1.247:3306/intranet";
String _userLogin = "intranet";
String _pwLogin = "tetris82";

// Futura DB
String _mssqlJdbcDriver = "com.microsoft.jdbc.sqlserver.SQLServerDriver";
String _urlFutura = "jdbc:microsoft:sqlserver://10.2.1.228:1433";
String _userFutura = "intranet";
String _pwFutura = "tetris";

// Uplod
String _uploadPath = "/var/tmp";
long _maxFileSize = 10*1024*1024;

// style image path
String _styleImgURL = "/image";

// Fault return invoice File URL
String _faultReturnInvoiceFileURL = "/image/Return";

// Memo \u00b0\u00fc\u00b7\u00c3 \u00ba\u00af\u00bc\u00f6
String _memoDataUrl = "/memo/upload";

// APESS SCM ID
String _apessID = "60171";

// Spec Sheet path
String _specSheetUrl = "/image/SPEC_SHEET";

// Spec Sheet upload path
String _specSheetUploadUrl = "/scan_spec_sheet";

// Sample Image Url
String _sampleIamgeUrl = "/image/SAMPLE_IMAGE";

// barcode file Image Url
String _barcodeFileUrl = "/image/Barcode";

// Invoice file path
String _invoiceFileUrl = "/order/inv_files";

// shipment file path
String _shipmentFileUrl = "/order/shipment_upload";

// Apess MU rate
double _MURate = 0.25;

// Ex-Factory Price Rate
double _EXRate = 0.04;


// Ex-Factory Price Rate for Apess2
double _EXRate2 = 0.04;

// Pronto DATA_AREA
//String _dataArea = "fft";
String _dataArea = "ffl";

// Pronto PIE Info
//String _pieIP = "10.2.1.226";
String _pieIP = "newffbpro.fastfuturebrands.com.au";
int _piePort = 7000;
//String _pieDataset = "apitest";
String _pieDataset = "apilive";

      out.write(_jsp_string2, 0, _jsp_string2.length);
      
String QTY_FORMAT = "###,##0";
String MONEY_FORMAT = "###,##0.00";

String M = request.getParameter("M");
String ag_supplier = request.getParameter("ag_supplier");
String ag_brand = request.getParameter("ag_brand");
String ag_date_type = request.getParameter("ag_date_type");
String ag_from_date = request.getParameter("ag_from_date");
String ag_to_date = request.getParameter("ag_to_date");
String ag_status = request.getParameter("ag_status");
String ag_po_no = request.getParameter("ag_po_no");
String ag_style_no = request.getParameter("ag_style_no");
String ag_orderby = request.getParameter("ag_orderby");
String ag_buyer = request.getParameter("ag_buyer");
String ag_mr = request.getParameter("ag_mr");
String ag_invoice_no = request.getParameter("ag_invoice_no");
if (M == null) M = "";
if (ag_supplier == null) ag_supplier = "";
if (ag_brand == null) ag_brand = "";
if (ag_date_type == null) ag_date_type = "SH";
if (ag_from_date == null || ag_to_date == null) {
  ag_from_date = DateUtil.getRelativeDateString(new java.util.Date(), 0, 0, -6, "dd/MM/yyyy");
  ag_to_date = DateUtil.getToday("dd/MM/yyyy");
}
if (ag_status == null) ag_status = "0";
if (ag_po_no == null) ag_po_no = "";
if (ag_style_no == null) ag_style_no = "";
if (ag_orderby == null) ag_orderby = "7";
if (ag_buyer == null) ag_buyer = "";
if (ag_mr == null) ag_mr = "";
if (ag_invoice_no == null) ag_invoice_no = "";

Connection connPronto = null;
Connection connScm = null;
dbconn.DBConnManager dbPool = null;
dbconn.MatrixDataSet matrix = null;
dbconn.MatrixDataSet matrix2 = null;
dbconn.MatrixDataSet matrix3 = null;
dbconn.MatrixDataSet matrix4 = null;
dbconn.MatrixDataSet matrix5 = null;
dbconn.MatrixDataSet matrix6 = null;
dbconn.DataProcess dataProcess = null;
String sql = "";
String sql2 = "";
String sql3 = "";
String sql4 = "";
String sql5 = "";
String sql6 = "";
int iRet = 0;
int iRet2 = 0;
int iRet3 = 0;
int iRet4 = 0;
int iRet5 = 0;
String outS = "";
double sum_unit_price_amount = 0.0d;
double sum_ex_factory_price_amount = 0.0d;

// query for po list
sql = " select  to_char(c.xpoa_ts_created+10/24, 'dd/mm/yyyy'), "
    + "         to_char(d.xpoa_ts_created+10/24, 'dd/mm/yyyy'), "
    + "         a.po_order_no, "
    + "         b.xspo_style, "
    + "         k.shm_description, "
    + "         case "
    + "           when a.po_order_status = '25' then 'Firm planned' "
    + "           when a.po_order_status between '40' and '80' then 'On order' "
    + "           when a.po_order_status = '90' then 'Completed' "
    + "           when a.po_order_status = '99' then 'Cancelled' "
    + "           else a.po_order_status "
    + "         end, "
    + "         to_char(a.po_order_date, 'yyyymmdd'), "
    + "         decode(to_char(b.ex_factory_date, 'yyyy'), '1900', '', to_char(b.ex_factory_date, 'dd/mm/yyyy')), "
    + "         to_char(a.po_arrival_date, 'dd/mm/yyyy'), "
    + "         f.sys_description, "
    + "         g.cr_shortname, "
    + "         e.spec_date, "
    + "         h.inspector, "
    + "         to_char(h.inspect_date, 'dd/mm/yyyy'), "
    + "         i.order_qty, "
    + "         b.vendor_price, "
    + "         h.ex_factory_price, "
    + "         b.xspo_discount, "
    + "         decode(a.po_currency_code, ' ', 'AUD', a.po_currency_code), "
    + "         b.xspo_trans_type, "
    + "         b.xspo_order_type, "
    + "         to_char(h.top_app_date, 'dd/mm/yyyy'), "
    + "         nvl(j.shipped_qty, 0), "
    + "         j.shipping_date, "
    + "         h.apess_comment, "
    + "         k.sht_category, "
    + "         case "
    //+ "           when g.cr_shortname like 'APESS3%' then 2 "
    + "           when n.order_control_yn <> 'Y' then 2 "
    + "           when a.po_order_status <> '99' "
    + "                and b.ex_factory_date is not null "
    + "                and to_char(b.ex_factory_date, 'yyyy') > '1900' "
    + "                and b.ex_factory_date < sysdate "
    + "                and j.shipping_date is null then 0 "
    + "           else 1 "
    + "         end ex_date_overdue, "
    + "         h.mr, "
    + "         l.invoice_no, "
    + "         b.xspo_rrp, "
    + "         nvl(o.rate, 0), "
    + "         n.order_control_yn, "
    + "         n.mu_yn "
    + " from    por5mf4 a "
    + "         inner join xstpu22 b "
    + "           on a.po_order_no = b.xspo_po_order_no "
    + "           and a.backorder_flag = b.backorder_flag "
    + "         left outer join xpoaudt0 c "
    + "           on a.po_order_no = c.xpoa_po_order_no "
    + "           and a.backorder_flag = c.backorder_flag "
    + "           and c.xpoa_change_type = 'STAT' "
    + "           and c.xpoa_status = '00' "
    + "           and c.xpoa_old_value = '00' "
    + "           and c.xpoa_new_value = '25' "
    + "         left outer join xpoaudt0 d "
    + "           on a.po_order_no = d.xpoa_po_order_no "
    + "           and a.backorder_flag = d.backorder_flag "
    + "           and d.xpoa_change_type = 'STAT' "
    + "           and d.xpoa_status = '25' "
    + "           and d.xpoa_old_value = '25' "
    + "           and d.xpoa_new_value = '40' "
    + "         left outer join  "
    + "         ( "
    + "           select  substr(e.ql_description, 1, instr(e.ql_description, ' ') - 1) style_no, "
    + "                   max(substr(substr(e.ql_description, instr(e.ql_description, ' ') + 1), 5) "
    + "                   || substr(substr(e.ql_description, instr(e.ql_description, ' ') + 1), 3, 2) "
    + "                   || substr(substr(e.ql_description, instr(e.ql_description, ' ') + 1), 1, 2)) spec_date "
    + "           from    qlinks0 e "
    + "           where   e.ql_data_area = '" + _dataArea + "' "
    + "           and     e.ql_table = 'xspo-style-purchase-order' "
    + "           and     substr(e.ql_description, 1, instr(e.ql_description, ' ') - 1) is not null "
    + "           group by substr(e.ql_description, 1, instr(e.ql_description, ' ') - 1) "
    + "         ) e "
    + "           on to_char(b.xspo_style) = e.style_no "
    + "         left outer join sys5tbl5 f "
    + "           on a.po_user_name = f.sys_tbl_code "
    + "           and f.sys_tbl_type = 'RR' "
    + "         inner join cre5mfi g "
    + "           on a.cre_accountcode = g.cre_accountcode "
    + "         left outer join po_style_etc@scm h "
    + "           on a.po_order_no = h.po_no "
    + "         inner join "
    + "         ( "
    + "           select  xsca_po_order_no, backorder_flag, sum(xsca_total_qty) order_qty "
    + "           from    xstcolal1 "
    + "           group by xsca_po_order_no, backorder_flag "
    + "         ) i "
    + "           on b.xspo_po_order_no = i.xsca_po_order_no "
    + "           and b.backorder_flag = i.backorder_flag "
    + "         left outer join "
    + "         ( "
    + "           select  a.po_no, a.shipping_date, sum(b.ttl_qty) shipped_qty "
    + "           from    packing_01t@scm a "
    + "                   inner join packing_03t@scm b "
    + "                     on a.packing_date||'' = b.packing_date "
    + "                     and a.po_no||'' = b.po_no "
    + "                     and a.style_no = b.style_no "
    //+ "           where   ( "
    //+ "                     a.supplier_id = '" + scmid + "' "
    //+ "                     or a.supplier_id in (select /*+ PUSH_SUBQ */ subid||'' from login_02t@scm where id = '" + scmid + "') "
    //+ "                     or a.supplier_id in (select id from login_01t@scm where name like 'APESS3%') ) "
    //+ "                   ) "
    + "           where   a.supplier_id in "
    + "                   ( "
    + "                     select  id "
    + "                     from    login_01t@scm "
    + "                     where   supplier_class in (select supplier_class from user_supplier_02t@scm where user_type = '" + usertype + "') "
    + "                   ) "
    + "           group by a.po_no, a.shipping_date "
    + "         ) j "
    + "           on a.po_order_no = j.po_no "
    + "         left outer join "
    + "         ( "
    + "           select z.stock_group, z.sht_category, y.shm_description "
    + "           from   stkhierachymst0 y "
    + "                  inner join stkhiertree3 z "
    + "                    on y.shm_code = z.sht_category "
    + "                    and y.shm_type = 3 "
    + "         ) k "
    + "           on b.xspo_stock_group = k.stock_group "
    + "         left outer join invoice_apess_02t@scm l "
    + "           on a.po_order_no = l.po_no "
    + "         inner join nad5mfa m "
    + "           on g.cre_accountcode = m.accountcode "
    + "         inner join user_supplier_02t@scm n "
    + "           on m.na_country_code = n.supplier_class "
    + "         left outer join supplier_commission@scm o "
    + "           on n.supplier_class = o.supplier_class "
    + "           and a.po_order_date between o.from_date and o.to_date "
    + " where   a.backorder_flag = ' ' "
    //+ " and     ( a.cre_accountcode = '" + scmid + "' "
    //+ "           or a.cre_accountcode in (select subid from login_02t@scm where id = '" + scmid + "') "
    //+ "           or a.cre_accountcode in (select id from login_01t@scm where name like 'APESS3%') ) "
    + " and     m.na_type = 'C' "
    + " and     n.user_type = '" + usertype + "' "
    + " and     ( a.po_order_status between '25' and '90' "
    + "           or (a.po_order_status = '99' and c.xpoa_ts_created is not null) ) ";

if (ag_po_no.length() > 0 || ag_style_no.length() > 0 || ag_invoice_no.length() > 0) {
  if (ag_po_no.length() > 0) {
    String sql_po_no = "'" + ag_po_no.replaceAll(",", "','") + "'";
    sql += " and    a.po_order_no in (" + sql_po_no + ") " ;
  }

  if (ag_style_no.length() > 0) {
    sql += " and    b.xspo_style like '" + ag_style_no + "%' " ;
  }

  if (ag_invoice_no.length() > 0) {
    sql += " and    l.invoice_no = '" + ag_invoice_no + "' ";
  }
} else {
  if (!ag_supplier.equals("")) {
    sql += " and    a.cre_accountcode = '" + ag_supplier + "' ";
  }

  if (!ag_brand.equals("")) {
    sql += " and    k.sht_category = '" + ag_brand + "' ";
  }

  if (!ag_buyer.equals("")) {
    sql += " and    a.po_user_name = '" + ag_buyer + "' ";
  }

  if (!ag_mr.equals("")) {
    sql += " and    h.mr = '" + ag_mr + "' ";
  }
  
  String tmpDate = "";
  if (ag_date_type.equals("SH")) {
    tmpDate = "b.ex_factory_date";
  } else if (ag_date_type.equals("DE")) {
    tmpDate = "a.po_arrival_date";
  } else if (ag_date_type.equals("PR")) {
    tmpDate = "c.xpoa_ts_created+10/24";
  //} else if (ag_date_type.equals("AS")) {
  //  tmpDate = "to_date(j.shipping_date, 'dd/mm/yy')";
  } else if (ag_date_type.equals("CF")) {
    tmpDate = "d.xpoa_ts_created+10/24";
  }

  sql += " and " + tmpDate + " >= to_date('" + ag_from_date + "', 'dd/mm/yyyy') "
       + " and " + tmpDate + " < to_date('" + ag_to_date + "', 'dd/mm/yyyy')+1 ";

  if (!ag_status.equals("")) {
    if (ag_status.equals("0")) {
      sql += " and    a.po_order_status between '25' and '90' ";
    } else if (ag_status.equals("40")) {
      sql += " and    a.po_order_status between '40' and '80' ";
    } else {
      sql += " and    a.po_order_status = '" + ag_status + "' ";
    }
  }
}

sql += " order by ex_date_overdue, ";

if ( ag_orderby.equals("1"))  {
  sql += " c.xpoa_ts_created ";
}
else if ( ag_orderby.equals("2"))  {
  sql += " f.sys_description ";
}
else if ( ag_orderby.equals("3"))  {
  sql += " a.po_order_no ";
}
else if ( ag_orderby.equals("4"))  {
  sql += " a.po_arrival_date " ;
}
else if ( ag_orderby.equals("5"))  {
  sql += " b.ex_factory_date " ;
}
else if ( ag_orderby.equals("6"))  {
  sql += " g.cr_shortname ";
}
else if ( ag_orderby.equals("7"))  {
  sql += " a.po_arrival_date, g.cr_shortname " ;
}
else if ( ag_orderby.equals("8"))  {
  sql += " substr(j.shipping_date, 6)||substr(j.shipping_date, 3, 2)||substr(j.shipping_date, 1, 2) ";
}
else if ( ag_orderby.equals("9"))  {
  sql += " h.mr ";
}
//out.println(sql);

// query for inspector list
sql2 =  " select  code, name, origin "
      + " from    vg_inspector "
      + " where   use_yn = 'Y' "
      + " and     user_type = '" + usertype + "' "
      + " order by code ";

// query for apess supplier list
sql3 =  " select  id, name "
      + " from    login_01t "
      + " where   supplier_class in (select supplier_class from user_supplier_02t where user_type = '" + usertype + "') "
      + " order by name ";

// query for buyer list
sql4 =  " select  distinct a.po_user_name, nvl(b.sys_description, a.po_user_name), b.sys_description "
      + " from    por5mf4 a "
      + "         left outer join sys5tbl5 b "
      + "           on a.po_user_name = b.sys_tbl_code "
      + "           and b.sys_tbl_type = 'RR' "
      + " where   a.backorder_flag = ' ' "
      + " and     trim(a.po_user_name) is not null "
      //+ " and     ( a.cre_accountcode = '" + scmid + "' "
      //+ "           or a.cre_accountcode in (select subid from login_02t@scm where id = '" + scmid + "') "
      //+ "           or a.cre_accountcode in (select id from login_01t@scm where name like 'APESS3%') ) "
      + " and     a.cre_accountcode in "
      + "         ( "
      + "           select  id "
      + "           from    login_01t@scm "
      + "           where   supplier_class in (select supplier_class from user_supplier_02t@scm where user_type = '" + usertype + "') "
      + "         ) "
      + " order by b.sys_description ";

// query for mr list
sql5 =  " select  adminid, adminname "
      + " from    admin_01t "
      //+ " where   admintype = 'C' "
      + " where   admintype = '" + usertype + "' "
      + " and     admingroup = 'M' "
      + " order by adminname ";

// read user brand code info
sql6 = " select  code, code_name "
     + " from    vg_common_code "
     + " where   type = 'USER_BRAND' "
     + " and     nvl(related_code, ' ') <> 'Z' "
     + " and     use_yn = 'Y' "
     + " order by sort_order ";

try {

  dbPool = DBConnManager.getInstance();
  connPronto = dbPool.getConnection("pronto");
  matrix = new dbconn.MatrixDataSet();
  matrix2 = new dbconn.MatrixDataSet();
  matrix3 = new dbconn.MatrixDataSet();
  matrix4 = new dbconn.MatrixDataSet();
  matrix5 = new dbconn.MatrixDataSet();
  matrix6 = new dbconn.MatrixDataSet();
  dataProcess = new dbconn.DataProcess();

  // po list
  iRet = dataProcess.RetrieveData(sql, matrix, connPronto);
  connPronto.commit();

  // inspector list
  connScm = dbPool.getConnection("intranet");
  iRet2 = dataProcess.RetrieveData(sql2, matrix2, connScm);

  // supplier list
  iRet3 = dataProcess.RetrieveData(sql3, matrix3, connScm);

  // buyer list
  iRet4 = dataProcess.RetrieveData(sql4, matrix4, connPronto);

  // mr list
  iRet5 = dataProcess.RetrieveData(sql5, matrix5, connScm);

  // brand list
  dataProcess.RetrieveData(sql6, matrix6, connScm);

} catch (Exception e) {
  if (connPronto != null) {
    try { connPronto.rollback(); } catch (Exception ex) {}
  }

  System.out.println("Exception in dsk_po_status : " + e.getMessage());
  throw e;
} finally {
  if (connPronto != null) {
    dbPool.freeConnection("pronto", connPronto);
  }

  if (connScm != null) {
    dbPool.freeConnection("intranet", connScm);
  }
}

// print po list
for (int i = 0; i < iRet; i++) {
  int j = 0;
  String pr_date = matrix.getRowData(i).getData(j++);
  String sc_confirmed_date = matrix.getRowData(i).getData(j++);
  String po_no = matrix.getRowData(i).getData(j++);
  String style_no = matrix.getRowData(i).getData(j++);
  String brandName = matrix.getRowData(i).getData(j++);
  String po_status = matrix.getRowData(i).getData(j++);
  String order_date = matrix.getRowData(i).getData(j++);
  String ex_factory_date = matrix.getRowData(i).getData(j++);
  String delivery_date = matrix.getRowData(i).getData(j++);
  String buyer = matrix.getRowData(i).getData(j++);
  String supplier_name = matrix.getRowData(i).getData(j++);
  String spec_date = matrix.getRowData(i).getData(j++);
  String inspector = matrix.getRowData(i).getData(j++);
  String inspect_date = matrix.getRowData(i).getData(j++);
  int order_qty = Integer.parseInt(matrix.getRowData(i).getData(j++));
  double currency_unit_price = Double.parseDouble(matrix.getRowData(i).getData(j++));
  String org_ex_factory_price = matrix.getRowData(i).getData(j++);
  double discount_price = Double.parseDouble(matrix.getRowData(i).getData(j++));
  String currency_type = matrix.getRowData(i).getData(j++);
  String trans_type = matrix.getRowData(i).getData(j++);
  String order_type = matrix.getRowData(i).getData(j++);
  String top_app_date = matrix.getRowData(i).getData(j++);
  int shipped_qty = Integer.parseInt(matrix.getRowData(i).getData(j++));
  String shipping_date = matrix.getRowData(i).getData(j++);
  String apess_comment = matrix.getRowData(i).getData(j++);
  String brand = matrix.getRowData(i).getData(j++);
  String ex_date_overdue = matrix.getRowData(i).getData(j++);
  String mr = matrix.getRowData(i).getData(j++);
  String invoice_no = matrix.getRowData(i).getData(j++);
  double rrp = Double.parseDouble(matrix.getRowData(i).getData(j++));
  double commission_rate = Double.parseDouble(matrix.getRowData(i).getData(j++));
  String orderControlYn = matrix.getRowData(i).getData(j++);
  String muYn = matrix.getRowData(i).getData(j++);

  // re-calculate price to include MU
/*
  if (currency_unit_price > 0.0d && supplier_name.toUpperCase().startsWith("APESS(")
      && order_date.compareTo("20090101") >= 0 && order_date.compareTo("20090630") <= 0) {
    if ((usertype.equals("P") && usergroup.equals("S")) 
        || (usertype.equals("P") && usergroup.equals("A") && M.equals("Y"))) {
      //currency_unit_price *= (1.0d + _MURate);
      currency_unit_price = Math.round(currency_unit_price*(1.0d + _MURate)*100.0d)/100.0d;
    }
  }
*/
  if (currency_unit_price > 0.0d && muYn.equals("Y")
      && order_date.compareTo("20090101") >= 0 && order_date.compareTo("20090630") <= 0) {
    if (usertype.startsWith("C") && (usergroup.equals("S") || (usergroup.equals("A") && M.equals("Y")))) {
      currency_unit_price = Math.round(currency_unit_price*(1.0d + _MURate)*100.0d)/100.0d;
    }
  }

  // calculate ex_factory_price
  double ex_factory_price = 0.0d;
  double ex_dc_price = 0.0d;

/*
  if (supplier_name.toUpperCase().startsWith("APESS(") || supplier_name.toUpperCase().startsWith("APESS2(")) {
    String tmp_start_date = "20101108";
    double tmp_rate = _EXRate;

    if (order_date.compareTo(tmp_start_date) < 0) {
      tmp_start_date = "20100531";
      tmp_rate = 0.05d;

      if (order_date.compareTo(tmp_start_date) < 0) {
        tmp_start_date = "20090701";
        tmp_rate = 0.15d;
  
        if (supplier_name.toUpperCase().startsWith("APESS2(")) {
          tmp_start_date = "20100315";
          tmp_rate = 0.07d;
        }
    
        if (order_date.compareTo(tmp_start_date) < 0) {
          tmp_rate = 0.0d;
        }
      }
    }

    if (!org_ex_factory_price.equals("")) {
      ex_factory_price = Double.parseDouble(org_ex_factory_price);
    } else {
      //ex_factory_price = currency_unit_price/(1.0d + tmp_rate);
      ex_factory_price = Math.round(currency_unit_price*100.0d/(1.0d + tmp_rate))/100.0d;
    }
    
    // calculate ex_dc_price
    if (discount_price > 0.0d && ex_factory_price > 0.0d) {
      tmp_rate = Math.round((currency_unit_price/ex_factory_price - 1)*100.0d)/100.0d;
      ex_dc_price = Math.round(discount_price*100.0d/(1.0d + tmp_rate))/100.0d;
    }
  }
*/
  if (orderControlYn.equals("Y")) {
    if (!org_ex_factory_price.equals("")) {
      ex_factory_price = Double.parseDouble(org_ex_factory_price);
    } else {
      ex_factory_price = Math.round(currency_unit_price*100.0d/(1.0d + commission_rate))/100.0d;
    }

    // calculate ex_dc_price
    if (discount_price > 0.0d && ex_factory_price > 0.0d) {
      double tmp_rate = Math.round((currency_unit_price/ex_factory_price - 1)*100.0d)/100.0d;
      ex_dc_price = Math.round(discount_price*100.0d/(1.0d + tmp_rate))/100.0d;
    }
  }

  // sum unit price amount and ex-factory price amount
  double unit_price_amount = 0.0d;
  double ex_factory_price_amount = 0.0d;

  //if (supplier_name.toUpperCase().startsWith("APESS(") || supplier_name.toUpperCase().startsWith("APESS2(")) {
  if (orderControlYn.equals("Y")) {
    if (currency_unit_price > 0.0d) {
      unit_price_amount = shipped_qty*(currency_unit_price - discount_price);
    }
    if (ex_factory_price > 0.0d) {
      ex_factory_price_amount = shipped_qty*(ex_factory_price - ex_dc_price);
    }

    sum_unit_price_amount += unit_price_amount;
    sum_ex_factory_price_amount += ex_factory_price_amount;
  }
  ///////////////

  if (shipping_date.length() == 8) {
    shipping_date = shipping_date.substring(0, 6) + "20" + shipping_date.substring(6);
  }

  String colour_code = "#FFFFF0";

  if (po_status.equals("Cancelled")) colour_code = "#FF8080";

  if (ex_date_overdue.equals("0")) {
    colour_code = "#FF0000";
  } else if (ex_date_overdue.equals("2")) {
    colour_code = "#ADD8E6";
  }

  if (!spec_date.equals("")) {
    spec_date = "<a href=\"javascript:fnView('" + po_no + "');\">" 
              + spec_date.substring(6) + "/" + spec_date.substring(4, 6) + "/" + spec_date.substring(0, 4) + "</a>";
  }

  /////////////////////////////////
  // set inspector as select option
  String inspectorOptions = "";
  boolean isFound = false;

  inspectorOptions += "<option value=''";
  if (inspector.equals("")) {
    inspectorOptions += " selected";
    isFound = true;
  }
  inspectorOptions += "></option>";

  for (int k = 0; k < iRet2; k++) {
    if (!isFound && inspector.equals(matrix2.getRowData(k).getData(0))) {
      inspectorOptions += "<option value='" + matrix2.getRowData(k).getData(0) + "' selected>"
                        + matrix2.getRowData(k).getData(0) + "-" + matrix2.getRowData(k).getData(1) + "</option>";
      isFound = true;
    } else {
      if (brand.equals(matrix2.getRowData(k).getData(2)) || matrix2.getRowData(k).getData(2).equals("0")) {
        inspectorOptions += "<option value='" + matrix2.getRowData(k).getData(0) + "'>"
                          + matrix2.getRowData(k).getData(0) +  "-" + matrix2.getRowData(k).getData(1) + "</option>";
      }
    }
  }

  if (!isFound) {
    inspectorOptions += "<option value='" + inspector + "' selected>" + inspector + "</option>";
  }
  /////////////////////////////////

  /////////////////////////////////
  // set mr as select option
  String mrOptions = "";
  isFound = false;

  mrOptions += "<option value=''";
  if (mr.equals("")) {
    mrOptions += " selected";
    isFound = true;
  }
  mrOptions += "></option>";

  for (int k = 0; k < iRet5; k++) {
    mrOptions += "<option value='" + matrix5.getRowData(k).getData(0) + "'";
    
    if (!isFound && mr.equals(matrix5.getRowData(k).getData(0))) {
      mrOptions += " selected";
      isFound = true;
    }

    mrOptions += ">" + matrix5.getRowData(k).getData(1) + "</option>";
  }

  if (!isFound) {
    mrOptions += "<option value='" + mr + "' selected>" + mr + "</option>";
  }
  /////////////////////////////////

  outS += "<tr align='center' bgcolor='" + colour_code + "'>"
        + " <td>" + (i+1) + "</td>"
        + " <td nowrap>" + pr_date + "</td>"
        + " <td nowrap>" + sc_confirmed_date + "</td>"
        + " <td>" + brandName + "</td>"
        + " <td><a href=\"javascript:fnView('" + po_no + "')\">" + po_no + "</td>"
        + " <td>" + style_no + "<input type='hidden' name='po_no' value='" + po_no + "'></td>"
        + " <td>" + supplier_name + "</td>"
        + " <td nowrap>" + ex_factory_date + "</td>"
        + " <td nowrap>" + delivery_date + "</td>"
        + " <td>" + trans_type + "</td>"
        + " <td>" + buyer + "</td>"
        + " <td><select name='mr'>" + mrOptions + "</select></td>"
        + " <td nowrap>"
        +   (order_type.equals("R") ? "<input type='hidden' name='top_app_date' value='" + top_app_date + "'>" + order_type
            : "<input type='text' name='top_app_date' size='10' value='" + top_app_date + "' style='cursor:hand' readonly "
              + "onclick=\"javascript:popFrame.fPopCalendar(this, this, document.all['popCal'], 'LEFT', event);\">"
              + "<a href=\"javascript:fnClearDate(" + i + ", 'T');\">X</a>") + "</td>"
        + " <td align='right'>" + StringUtil.formatNumber(order_qty, QTY_FORMAT) + "</td>"
        + " <td align='right'>" + StringUtil.formatNumber(rrp, MONEY_FORMAT) + "</td>"
        + " <td align='right'>" + (currency_unit_price > 0.0d ? StringUtil.formatNumber(currency_unit_price, MONEY_FORMAT) : "TBA") + "</td>"
        + " <td align='right' " + (!org_ex_factory_price.equals("") ? "style='color:blue;'" : "") + ">"
        //+ (supplier_name.toUpperCase().startsWith("APESS(") || supplier_name.toUpperCase().startsWith("APESS2(")
        + (orderControlYn.equals("Y") ? (ex_factory_price > 0.0d ? StringUtil.formatNumber(ex_factory_price, MONEY_FORMAT) : "TBA") : "") + "</td>"
        + " <td align='right'>"
        +   (discount_price > 0.0d ? StringUtil.formatNumber(discount_price, MONEY_FORMAT) : "") + "</td>"
        + " <td align='right'>"
        +   (ex_dc_price > 0.0d ? StringUtil.formatNumber(ex_dc_price, MONEY_FORMAT) : "") + "</td>"
        + " <td>" + currency_type + "</td>"
        + " <td>" + po_status + "</td>"
        + " <td>" + spec_date + "</td>"
        + " <td></td>"                      // for sample approve date
        + " <td><select name='inspector'>" + inspectorOptions + "</select></td>"
        + " <td nowrap><input type='text' name='inspect_date' size='10' value='" + inspect_date + "' style='cursor:hand' readonly"
        + "       onclick=\"javascript:popFrame.fPopCalendar(this, this, document.all['popCal'], 'LEFT', event);\">"
        + "       <a href=\"javascript:fnClearDate(" + i + ", 'I');\">X</a></td>"
        + " <td align='right'>" + StringUtil.formatNumber(shipped_qty, QTY_FORMAT) + "</td>"
        + " <td align='right'>"
        //+ (supplier_name.toUpperCase().startsWith("APESS(") || supplier_name.toUpperCase().startsWith("APESS2(")
        + (orderControlYn.equals("Y") ? (currency_unit_price > 0.0d ? StringUtil.formatNumber(unit_price_amount, MONEY_FORMAT) : "") : "") + "</td>"
        + " <td align='right'>"
        //+ (supplier_name.toUpperCase().startsWith("APESS(") || supplier_name.toUpperCase().startsWith("APESS2(")
        + (orderControlYn.equals("Y") ? (ex_factory_price > 0.0d ? StringUtil.formatNumber(ex_factory_price_amount, MONEY_FORMAT) : "") : "") + "</td>"
        + " <td nowrap>" + shipping_date + "</td>"
        + " <td>" + invoice_no + "</td>"
        + " <td><input type='text' name='apess_comment' value='" + apess_comment + "' size='30' maxlength='30'></td>"
        + "</tr>";
}

// print supplier list
String supplierList = "<option value=''>All</option>";
for (int i = 0; i < iRet3; i++) {
  int j = 0;
  String supplier_id = matrix3.getRowData(i).getData(j++);
  String supplier_name = matrix3.getRowData(i).getData(j++);

  supplierList += "<option value='"+ supplier_id + "'" 
                + (ag_supplier.equals(supplier_id) ? " selected" : "") + ">" 
                + supplier_id + "-" + supplier_name + "</option>";
}

// print buyer list
String buyerList = "<option value=''>All</option>";
for (int i = 0; i < iRet4; i++) {
  int j = 0;
  String buyer_id = matrix4.getRowData(i).getData(j++);
  String buyer_name = matrix4.getRowData(i).getData(j++);

  buyerList += "<option value='"+ buyer_id + "'" 
             + (ag_buyer.equals(buyer_id) ? " selected" : "") + ">" 
             + buyer_name + "</option>";
}

// MR option list
String mrList = "<option value=''>All</option>";
for (int i = 0; i < iRet5; i++) {
  mrList += "<option value='"+ matrix5.getRowData(i).getData(0) + "'" 
             + (ag_mr.equals(matrix5.getRowData(i).getData(0)) ? " selected" : "") + ">" 
             + matrix5.getRowData(i).getData(1) + "</option>";
}

// print user brand options
String userBrandOptions = "<option value=''>All</option>";
for (int i = 0; i < matrix6.getRowCount(); i++) {
  int j = 0;
  String code = matrix6.getRowData(i).getData(j++);
  String codeName = matrix6.getRowData(i).getData(j++);

  userBrandOptions += "<option value='" + code + "'"
                    + (ag_brand.equals(code) ? " selected" : "") + ">" + codeName + "</option>";
}

      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print(( M.equals("Y") ? "+" : "" ));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print(( M ));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print(( supplierList ));
      out.write(_jsp_string6, 0, _jsp_string6.length);
      out.print(( userBrandOptions ));
      out.write(_jsp_string7, 0, _jsp_string7.length);
      out.print(( ag_date_type.equals("SH") ? "selected" : "" ));
      out.write(_jsp_string8, 0, _jsp_string8.length);
      out.print(( ag_date_type.equals("DE") ? "selected" : "" ));
      out.write(_jsp_string9, 0, _jsp_string9.length);
      out.print(( ag_date_type.equals("PR") ? "selected" : "" ));
      out.write(_jsp_string10, 0, _jsp_string10.length);
      out.print(( ag_date_type.equals("CF") ? "selected" : "" ));
      out.write(_jsp_string11, 0, _jsp_string11.length);
      out.print(( ag_from_date ));
      out.write(_jsp_string12, 0, _jsp_string12.length);
      out.print(( ag_to_date ));
      out.write(_jsp_string13, 0, _jsp_string13.length);
       if(ag_status.equals(""))  out.print("SELECTED");  
      out.write(_jsp_string14, 0, _jsp_string14.length);
       if(ag_status.equals("0"))  out.print("SELECTED");  
      out.write(_jsp_string15, 0, _jsp_string15.length);
       if(ag_status.equals("25")) out.print("SELECTED"); 
      out.write(_jsp_string16, 0, _jsp_string16.length);
       if(ag_status.equals("40")) out.print("SELECTED"); 
      out.write(_jsp_string17, 0, _jsp_string17.length);
       if(ag_status.equals("90")) out.print("SELECTED"); 
      out.write(_jsp_string18, 0, _jsp_string18.length);
       if(ag_status.equals("99")) out.print("SELECTED"); 
      out.write(_jsp_string19, 0, _jsp_string19.length);
      out.print(( buyerList ));
      out.write(_jsp_string20, 0, _jsp_string20.length);
      out.print(( mrList ));
      out.write(_jsp_string21, 0, _jsp_string21.length);
      out.print(( ag_invoice_no ));
      out.write(_jsp_string22, 0, _jsp_string22.length);
      out.print(( ag_po_no ));
      out.write(_jsp_string23, 0, _jsp_string23.length);
      out.print(( ag_style_no ));
      out.write(_jsp_string24, 0, _jsp_string24.length);
       if(ag_orderby.equals("1")) out.print("SELECTED"); 
      out.write(_jsp_string25, 0, _jsp_string25.length);
       if(ag_orderby.equals("2")) out.print("SELECTED"); 
      out.write(_jsp_string26, 0, _jsp_string26.length);
       if(ag_orderby.equals("3")) out.print("SELECTED"); 
      out.write(_jsp_string27, 0, _jsp_string27.length);
       if(ag_orderby.equals("4")) out.print("SELECTED"); 
      out.write(_jsp_string28, 0, _jsp_string28.length);
       if(ag_orderby.equals("5")) out.print("SELECTED"); 
      out.write(_jsp_string29, 0, _jsp_string29.length);
       if(ag_orderby.equals("6")) out.print("SELECTED"); 
      out.write(_jsp_string30, 0, _jsp_string30.length);
       if(ag_orderby.equals("7")) out.print("SELECTED"); 
      out.write(_jsp_string31, 0, _jsp_string31.length);
       if(ag_orderby.equals("8")) out.print("SELECTED"); 
      out.write(_jsp_string32, 0, _jsp_string32.length);
       if(ag_orderby.equals("9")) out.print("SELECTED"); 
      out.write(_jsp_string33, 0, _jsp_string33.length);
      out.print(( M ));
      out.write(_jsp_string34, 0, _jsp_string34.length);
      out.print(( ag_supplier ));
      out.write(_jsp_string35, 0, _jsp_string35.length);
      out.print(( ag_brand ));
      out.write(_jsp_string36, 0, _jsp_string36.length);
      out.print(( ag_date_type ));
      out.write(_jsp_string37, 0, _jsp_string37.length);
      out.print(( ag_from_date ));
      out.write(_jsp_string38, 0, _jsp_string38.length);
      out.print(( ag_to_date ));
      out.write(_jsp_string39, 0, _jsp_string39.length);
      out.print(( ag_status ));
      out.write(_jsp_string40, 0, _jsp_string40.length);
      out.print(( ag_po_no ));
      out.write(_jsp_string41, 0, _jsp_string41.length);
      out.print(( ag_style_no ));
      out.write(_jsp_string42, 0, _jsp_string42.length);
      out.print(( ag_orderby ));
      out.write(_jsp_string43, 0, _jsp_string43.length);
      out.print(( ag_buyer ));
      out.write(_jsp_string44, 0, _jsp_string44.length);
      out.print(( ag_mr ));
      out.write(_jsp_string45, 0, _jsp_string45.length);
      out.print(( ag_invoice_no ));
      out.write(_jsp_string46, 0, _jsp_string46.length);
      out.print(( outS ));
      out.write(_jsp_string47, 0, _jsp_string47.length);
      out.print(( StringUtil.formatNumber(sum_unit_price_amount, MONEY_FORMAT) ));
      out.write(_jsp_string48, 0, _jsp_string48.length);
      out.print(( StringUtil.formatNumber(sum_ex_factory_price_amount, MONEY_FORMAT) ));
      out.write(_jsp_string49, 0, _jsp_string49.length);
      out.print(( M ));
      out.write(_jsp_string34, 0, _jsp_string34.length);
      out.print(( ag_supplier ));
      out.write(_jsp_string35, 0, _jsp_string35.length);
      out.print(( ag_brand ));
      out.write(_jsp_string36, 0, _jsp_string36.length);
      out.print(( ag_date_type ));
      out.write(_jsp_string37, 0, _jsp_string37.length);
      out.print(( ag_from_date ));
      out.write(_jsp_string38, 0, _jsp_string38.length);
      out.print(( ag_to_date ));
      out.write(_jsp_string39, 0, _jsp_string39.length);
      out.print(( ag_status ));
      out.write(_jsp_string40, 0, _jsp_string40.length);
      out.print(( ag_po_no ));
      out.write(_jsp_string41, 0, _jsp_string41.length);
      out.print(( ag_style_no ));
      out.write(_jsp_string42, 0, _jsp_string42.length);
      out.print(( ag_orderby ));
      out.write(_jsp_string43, 0, _jsp_string43.length);
      out.print(( ag_buyer ));
      out.write(_jsp_string44, 0, _jsp_string44.length);
      out.print(( ag_mr ));
      out.write(_jsp_string45, 0, _jsp_string45.length);
      out.print(( ag_invoice_no ));
      out.write(_jsp_string50, 0, _jsp_string50.length);
      
out.println(CopyRightLogo());

      out.write(_jsp_string51, 0, _jsp_string51.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 5783496155892875126L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("order/dsk_po_status.jsp"), -2016596953340313459L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("login_check.jsp"), 5313538553479869376L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("bottom_line.jsp"), 5941552803368297242L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("common/CommonVars.jsp"), 5055347195946766837L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("common/calendar/calendar.htm"), 2970746783289767368L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string4;
  private final static char []_jsp_string20;
  private final static char []_jsp_string36;
  private final static char []_jsp_string44;
  private final static char []_jsp_string5;
  private final static char []_jsp_string26;
  private final static char []_jsp_string35;
  private final static char []_jsp_string11;
  private final static char []_jsp_string34;
  private final static char []_jsp_string1;
  private final static char []_jsp_string3;
  private final static char []_jsp_string30;
  private final static char []_jsp_string41;
  private final static char []_jsp_string6;
  private final static char []_jsp_string2;
  private final static char []_jsp_string10;
  private final static char []_jsp_string46;
  private final static char []_jsp_string48;
  private final static char []_jsp_string19;
  private final static char []_jsp_string29;
  private final static char []_jsp_string47;
  private final static char []_jsp_string21;
  private final static char []_jsp_string40;
  private final static char []_jsp_string28;
  private final static char []_jsp_string37;
  private final static char []_jsp_string50;
  private final static char []_jsp_string51;
  private final static char []_jsp_string16;
  private final static char []_jsp_string33;
  private final static char []_jsp_string17;
  private final static char []_jsp_string8;
  private final static char []_jsp_string13;
  private final static char []_jsp_string14;
  private final static char []_jsp_string7;
  private final static char []_jsp_string49;
  private final static char []_jsp_string24;
  private final static char []_jsp_string31;
  private final static char []_jsp_string22;
  private final static char []_jsp_string0;
  private final static char []_jsp_string45;
  private final static char []_jsp_string39;
  private final static char []_jsp_string25;
  private final static char []_jsp_string23;
  private final static char []_jsp_string15;
  private final static char []_jsp_string43;
  private final static char []_jsp_string9;
  private final static char []_jsp_string38;
  private final static char []_jsp_string32;
  private final static char []_jsp_string18;
  private final static char []_jsp_string27;
  private final static char []_jsp_string12;
  private final static char []_jsp_string42;
  static {
    _jsp_string4 = "</td>\n</tr>\n<tr>\n  <td width=\"100%\" height=\"2\" colspan=\"2\"><hr width=\"100%\"></td>\n</tr>\n<tr>\n  <td width=\"100%\" height=\"10\" colspan=\"2\"></td>\n</tr>\n</table>\n\n<table width=\"99%\" border=\"0\" cellspacing=\"1\" cellpadding=\"2\" align=\"center\" class=\"table_bg\">\n<FORM name='frmMain' ACTION=\"dsk_po_status.jsp\" METHOD=POST>\n<input type='hidden' name='M' value='".toCharArray();
    _jsp_string20 = "</SELECT></td>\n  <td class=\"table_header_center\">MR</td>\n  <td class=\"table_bg_bright\"><SELECT NAME='ag_mr'>".toCharArray();
    _jsp_string36 = "'>\n<input type='hidden' name='ag_date_type' value='".toCharArray();
    _jsp_string44 = "'>\n<input type='hidden' name='ag_mr' value='".toCharArray();
    _jsp_string5 = "'>\n<input type='hidden' name='po_no_selected'>\n<tr>\n  <td width=\"10%\" class=\"table_header_center\">Supplier</td>\n  <td width=\"32%\" class=\"table_bg_bright\"><SELECT NAME='ag_supplier'>".toCharArray();
    _jsp_string26 = "> Buyer </OPTION>\n    <OPTION value=\"3\" ".toCharArray();
    _jsp_string35 = "'>\n<input type='hidden' name='ag_brand' value='".toCharArray();
    _jsp_string11 = ">CF Date</option>\n    </select>\n    <input type='text' name='ag_from_date' size='10' value='".toCharArray();
    _jsp_string34 = "'>\n<input type='hidden' name='ag_supplier' value='".toCharArray();
    _jsp_string1 = "\n\n\n\n".toCharArray();
    _jsp_string3 = "\n<HTML>\n<HEAD>\n<link href=\"/common/css/style.css\" rel=\"stylesheet\" type=\"text/css\">\n<script language=\"javaScript\" src=\"/common/js/util.js\"></script>\n<SCRIPT LANGUAGE=JavaScript>\nfunction fnSubmit(frm)\n{\n  frm.ag_po_no.value = jf_AllTrim(frm.ag_po_no.value);\n  frm.ag_style_no.value = jf_AllTrim(frm.ag_style_no.value);\n  frm.ag_invoice_no.value = jf_AllTrim(frm.ag_invoice_no.value);\n  frm.submit();\n}\n\nfunction fnView(po_no_selected) {\n  frmMain.po_no_selected.value = po_no_selected;\n  frmMain.action = \"./po_detail.jsp\";\n  frmMain.submit();\n}\n\nfunction fnSave(frm) {\n  if (frm.po_no) {\n    if (confirm(\"Are you sure to save these data?\")) {\n      frm.action = './dsk_po_status_save.jsp';\n      frm.submit();\n    }\n  }\n}\n\nfunction fnExcel(frm) {\n  if (confirm(\"Do you want to download these data as an excel file?\"))\n  {\n    frm.action=\"./dsk_po_status_excel.jsp\";\n    frm.target = hidenFrame.name;\n    frm.submit();\n  }\n}\n\nfunction fnClearDate(idx, dateType) {\n  with (document.form2) {\n    if (inspect_date.length) {\n      if (dateType == 'I') {\n        inspect_date[idx].value = '';\n      } else if (dateType == 'T') {\n        top_app_date[idx].value = '';\n      }\n    } else {\n      if (dateType == 'I') {\n        inspect_date.value = '';\n      } else if (dateType == 'T') {\n        top_app_date.value = '';\n      }\n    }\n  }\n}\n</SCRIPT>\n</HEAD>\n<body leftmargin=\"0\" topmargin=\"0\" marginwidth=\"0\" marginheight=\"0\">\n<table width=\"840\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n<tr><td>\n\n<table width=\"99%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\n<tr>\n  <td width=\"100%\" height=\"15\" colspan=\"2\"></td>\n</tr>\n<tr>\n  <td width=\"3%\"><img src=\"/img/title_icon.gif\"></td>\n  <td width=\"*\" class=\"left_title\">Purchase Order History".toCharArray();
    _jsp_string30 = "> Supplier </OPTION>\n    <OPTION value=\"7\" ".toCharArray();
    _jsp_string41 = "'>\n<input type='hidden' name='ag_style_no' value='".toCharArray();
    _jsp_string6 = "</SELECT></td>\n  <td width=\"10%\" class=\"table_header_center\">Brand</td>\n  <td width=\"19%\" class=\"table_bg_bright\"><SELECT NAME='ag_brand'>".toCharArray();
    _jsp_string2 = "\n<Div id='popCal' style='POSITION:absolute;visibility:hidden;border:1px ridge;width:10'>\n  <iframe name=\"popFrame\" src=\"/common/calendar/popcjs.htm\" frameborder=\"0\" style=\"border:1 solid #EBF6FD\"  frameborder=\"0\" scrolling=\"no\" width=176 height=215>\n  </iframe>\n</DIV>\n<!--SCRIPT event=onclick() for=document>document.all['popCal'].style.visibility = \"hidden\";</SCRIPT-->\n<script language='javascript'>\nfunction setVisibility() {\n  document.all['popCal'].style.visibility = 'hidden';\n}\n\ndocument.onclick = setVisibility;\n</script>\n".toCharArray();
    _jsp_string10 = ">PR Date</option>\n    <option value='CF' ".toCharArray();
    _jsp_string46 = "'>\n<TR class=\"table_header_center\">\n<TD>No</TD>\n<TD>PR Date</TD>\n<TD>Confirmed</TD>\n<TD>Brand</TD>\n<TD>PO No.</TD>\n<TD>Style No.</TD>\n<TD>Supplier</TD>\n<TD>Ship Date</TD>\n<TD>Delivery</TD>\n<TD>Trans Type</TD>\n<TD>Buyer</TD>\n<TD>MR</TD>\n<TD>Top App Date</TD>\n<TD>Order Qty</TD>\n<TD>RRP</TD>\n<TD>Unit Price</TD>\n<TD>Ex-Factory Price</TD>\n<TD>D/C Price</TD>\n<TD>Ex-D/C Price</TD>\n<TD>Currency</TD>\n<TD>PO Status</TD>\n<TD>Spec Sheet</TD>\n<TD>Approve Date</TD>\n<TD>Inspector</TD>\n<TD>Inspect Date</TD>\n<TD>Shipped Qty</TD>\n<TD>Amount(U/P)</TD>\n<TD>Amount(F/P)</TD>\n<TD>Act. Ship Date</TD>\n<TD>Invoice No.</TD>\n<TD>Comment</TD>\n</TR>\n".toCharArray();
    _jsp_string48 = "</td>\n  <td>".toCharArray();
    _jsp_string19 = "> Cancelled </OPTION>\n    </SELECT></td>\n</tr>\n<tr>\n  <td class=\"table_header_center\">Buyer</td>\n  <td class=\"table_bg_bright\"><SELECT NAME='ag_buyer'>".toCharArray();
    _jsp_string29 = "> Ship Date </OPTION>\n    <OPTION value=\"6\" ".toCharArray();
    _jsp_string47 = "\n<tr align='right' class='table_bg_bright'>\n  <td colspan='26'>Total Amount</td>\n  <td>".toCharArray();
    _jsp_string21 = "</SELECT></td>\n  <td class=\"table_header_center\">Invoice#</td>\n  <td class=\"table_bg_bright\"><input type=text name='ag_invoice_no' value='".toCharArray();
    _jsp_string40 = "'>\n<input type='hidden' name='ag_po_no' value='".toCharArray();
    _jsp_string28 = "> Del. Date </OPTION>\n    <OPTION value=\"5\" ".toCharArray();
    _jsp_string37 = "'>\n<input type='hidden' name='ag_from_date' value='".toCharArray();
    _jsp_string50 = "'>\n</form>\n</TABLE>\n</td></tr></table>\n\n<table width=\"840\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"><tr><td>\n".toCharArray();
    _jsp_string51 = "\n</td></tr></table>\n<iframe width=\"0\" height=\"0\" name=\"hidenFrame\"></iframe>\n</BODY>\n</HTML>\n".toCharArray();
    _jsp_string16 = "> Firm planned </OPTION>\n    <OPTION value=\"40\" ".toCharArray();
    _jsp_string33 = "> MR </OPTION>\n    </SELECT></td>\n</tr>\n</form>\n</table>\n<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n<tr>\n  <td width=\"100%\" height=\"15\"></td>\n</tr>\n</table>\n</td></tr></table>\n\n<table width=\"2700\" border=\"0\" cellspacing=\"0\" cellpadding=\"3\"><tr><td>\n<TABLE border=0 width=99% CELLPADDING=0 CELLSPACING=1 class=\"table_bg\">\n<form name='form2' method='post'>\n<input type='hidden' name='M' value='".toCharArray();
    _jsp_string17 = "> On order </OPTION>\n    <OPTION value=\"90\" ".toCharArray();
    _jsp_string8 = ">SH Date</option>\n    <option value='DE' ".toCharArray();
    _jsp_string13 = "' style='cursor:hand' readonly\n    onclick=\"javascript:popFrame.fPopCalendar(this, this, document.all['popCal'], 'RIGHT', event);\">\n    </td>\n  <td class=\"table_header_center\">PO Status</td>\n  <td class=\"table_bg_bright\"><SELECT NAME='ag_status'>\n    <OPTION value=\"\" ".toCharArray();
    _jsp_string14 = "> All </OPTION>\n    <OPTION value=\"0\" ".toCharArray();
    _jsp_string7 = "</SELECT></td>\n  <td width=\"29%\" class=\"table_bg_bright_center\" colspan='2' rowspan='2'><INPUT TYPE='BUTTON' VALUE=\"Search\" ONCLICK='fnSubmit(this.form)'>\n    <input type='button' value='Excel' onclick='fnExcel(document.form3);'>\n    <input type='button' value='Print' onclick='self.print();'></td>\n</tr>\n<tr>\n  <td class=\"table_header_center\">Date</td>\n  <td class=\"table_bg_bright\"><select name='ag_date_type'>\n    <option value='SH' ".toCharArray();
    _jsp_string49 = "</td>\n  <td colspan='3'></td>\n</tr>\n<tr>\n  <td align='center' class='table_bg_bright' colspan='31'><input type='button' value='Save' onclick='fnSave(this.form);'>\n    <input type='reset' value='Reset'></td>\n</tr>\n</form>\n<form name='form3' method='post'>\n<input type='hidden' name='M' value='".toCharArray();
    _jsp_string24 = "' size='10' maxlength='6'></td>\n  <td width=\"10%\" class=\"table_header_center\">Order by</td>\n  <td width=\"19%\" class=\"table_bg_bright\"><SELECT NAME='ag_orderby'>\n    <OPTION value=\"1\" ".toCharArray();
    _jsp_string31 = "> Del. Date+Supplier </OPTION>\n    <OPTION value=\"8\" ".toCharArray();
    _jsp_string22 = "' size='15' maxlength='15'></td>\n</tr>\n<tr>\n  <td class=\"table_header_center\">PO#</td>\n  <td class=\"table_bg_bright\"><input type=text name='ag_po_no' value='".toCharArray();
    _jsp_string0 = "\n\n\n\n\n".toCharArray();
    _jsp_string45 = "'>\n<input type='hidden' name='ag_invoice_no' value='".toCharArray();
    _jsp_string39 = "'>\n<input type='hidden' name='ag_status' value='".toCharArray();
    _jsp_string25 = "> PR Date </OPTION>\n    <OPTION value=\"2\" ".toCharArray();
    _jsp_string23 = "' size='40' maxlength='200'></td>\n  <td class=\"table_header_center\">Style#</td>\n  <td class=\"table_bg_bright\"><input type=text name='ag_style_no' value='".toCharArray();
    _jsp_string15 = "> All-exc.canceled </OPTION>\n    <OPTION value=\"25\" ".toCharArray();
    _jsp_string43 = "'>\n<input type='hidden' name='ag_buyer' value='".toCharArray();
    _jsp_string9 = ">DE Date</option>\n    <option value='PR' ".toCharArray();
    _jsp_string38 = "'>\n<input type='hidden' name='ag_to_date' value='".toCharArray();
    _jsp_string32 = "> Act. Ship Date </OPTION>\n    <OPTION value=\"9\" ".toCharArray();
    _jsp_string18 = "> Completed </OPTION>\n    <OPTION value=\"99\" ".toCharArray();
    _jsp_string27 = "> PO No. </OPTION>\n    <OPTION value=\"4\" ".toCharArray();
    _jsp_string12 = "' style='cursor:hand' readonly\n    onclick=\"javascript:popFrame.fPopCalendar(this, this, document.all['popCal'], 'RIGHT', event);\">\n    ~\n    <input type='text' name='ag_to_date' size='10' value='".toCharArray();
    _jsp_string42 = "'>\n<input type='hidden' name='ag_orderby' value='".toCharArray();
  }
}
