/*
 * JSP generated by Resin-3.1.9 (built Mon, 13 Apr 2009 11:09:12 PDT)
 */

package _jsp._order;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.io.*;
import java.sql.*;
import java.util.*;
import dbconn.*;
import common.util.*;

public class _packing_0made__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;


  //-------------------------------------------
  // CopyRightLogo
  //
  //-------------------------------------------
  String CopyRightLogo()
  {
    String str;
    str = "<table width='99%' border='0' cellspacing='0' cellpadding='0' align='center'>";
    str += "<tr><td width='100%' height='2' align='center'>";
    str += "<HR width=100% size=2></td></tr>";
    str += "<tr><td width='100%' align='center'>";
    str += "<FONT size=2 >&copy;Copyright 2010 </font>";
    str += "<FONT size=2 color=green>Fast Future Brands Pty Ltd. All Rights Reserved.</FONT><BR>";
    str += "<FONT size=2> For more information,please contact</font> <FONT size=2 color=blue><A href='mailto:scm@ffb.net.au'>scm@ffb.net.au</A></FONT>";
    str += "</td></tr></table>";

    return (String)str;
  }

  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, "/error.jsp", session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
response.setHeader("Pragma","no-cache"); //HTTP 1.0
response.setDateHeader ("Expires", 0);
response.setHeader("Cache-Control","no-cache"); //HTTP 1.1

String scmid = "";
String scmnm = "";
String usertype = "";
String usergroup = "";
//String scmsubids = "";
String _adminid = "";
String _adminname = "";
String _admingroup = "";
String _apessid = "";
String _apessname = "";

try{
  scmid = (String) session.getAttribute("scmid");
  _adminid = (String) session.getAttribute("adminid");

  if( (scmid == null || scmid.length() == 0 || scmid.equals("null"))
      && (_adminid == null || _adminid.length() == 0 || _adminid.equals("null")) ) {
    response.sendRedirect("/login_first.html");
    return;
  }

  _adminname = (String) session.getAttribute("adminname");

  _apessid = (String) session.getAttribute("apessid");
  _apessname = (String) session.getAttribute("apessname");

  scmnm = (String) session.getAttribute("scmnm");

  usertype = (String) session.getAttribute("usertype");
  if (usertype == null) usertype = "";

  usergroup = (String) session.getAttribute("usergroup");
  if (usergroup == null) usergroup = "";

  //scmsubids = (String) session.getAttribute("scmsubids");
  //session.setMaxInactiveInterval(60*60);

}catch( Exception e ) {
  response.sendRedirect("/login_first.html");
  return;
}

      out.write('\n');
      
// Intranet DB
String _mysqlJdbcDriver = "com.mysql.jdbc.Driver";
String _urlLogin = "jdbc:mysql://10.2.1.247:3306/intranet";
String _userLogin = "intranet";
String _pwLogin = "tetris82";

// Futura DB
String _mssqlJdbcDriver = "com.microsoft.jdbc.sqlserver.SQLServerDriver";
String _urlFutura = "jdbc:microsoft:sqlserver://10.2.1.228:1433";
String _userFutura = "intranet";
String _pwFutura = "tetris";

// Uplod
String _uploadPath = "/var/tmp";
long _maxFileSize = 10*1024*1024;

// style image path
String _styleImgURL = "/image";

// Fault return invoice File URL
String _faultReturnInvoiceFileURL = "/image/Return";

// Memo \u00b0\u00fc\u00b7\u00c3 \u00ba\u00af\u00bc\u00f6
String _memoDataUrl = "/memo/upload";

// APESS SCM ID
String _apessID = "60171";

// Spec Sheet path
String _specSheetUrl = "/image/SPEC_SHEET";

// Spec Sheet upload path
String _specSheetUploadUrl = "/scan_spec_sheet";

// Sample Image Url
String _sampleIamgeUrl = "/image/SAMPLE_IMAGE";

// barcode file Image Url
String _barcodeFileUrl = "/image/Barcode";

// Invoice file path
String _invoiceFileUrl = "/order/inv_files";

// shipment file path
String _shipmentFileUrl = "/order/shipment_upload";

// Apess MU rate
double _MURate = 0.25;

// Ex-Factory Price Rate
double _EXRate = 0.04;


// Ex-Factory Price Rate for Apess2
double _EXRate2 = 0.04;

// Pronto DATA_AREA
//String _dataArea = "fft";
String _dataArea = "ffl";

// Pronto PIE Info
//String _pieIP = "10.2.1.226";
String _pieIP = "newffbpro.fastfuturebrands.com.au";
int _piePort = 7000;
//String _pieDataset = "apitest";
String _pieDataset = "apilive";

      out.write(_jsp_string1, 0, _jsp_string1.length);
      
String QTY_FORMAT = "###,##0";
int LINE_SIZE = 8;

String po_no_selected = request.getParameter("po_no_selected");
String packing_date = request.getParameter("packing_date");
String supplier_id = request.getParameter("supplier_id");

String supplier_name = "";
String brand = "";
String style_no = "";
String buyer = "";
String season = "";
String trans_type = "";
String delivery_date = "";
Map colourRatioMap = new HashMap();

String shipping_date = "";
String supplier_stkcd = "";
String others = "";
int packs_carton = 0;
String[] pack_lines = new String[LINE_SIZE];

int size1_qty_total = 0;
int size2_qty_total = 0;
int size3_qty_total = 0;
int size4_qty_total = 0;
int size5_qty_total = 0;
int size6_qty_total = 0;
int ttl_qty_total = 0;
int ttl_pqty_total = 0;
int ttl_ctn_total = 0;

Connection connPronto = null;
Connection connScm = null;
dbconn.DBConnManager dbPool = null;
dbconn.MatrixDataSet matrix = null;
dbconn.MatrixDataSet matrix2 = null;
dbconn.MatrixDataSet matrix3 = null;
dbconn.DataProcess dataProcess = null;
String sql = "";
String sql2 = "";
String sql3 = "";
int iRet = 0;
int iRet2 = 0;
int iRet3 = 0;
String outS = "";

// po detail query
sql = " select  c.cr_shortname, "
    + "         d.shm_description, "
    + "         b.xspo_style, "
    + "         nvl(e.sys_description, a.po_user_name), "
    + "         b.season_and_seq, "
    + "         b.xspo_trans_type, "
    + "         to_char(a.po_arrival_date, 'dd/mm/yyyy'), "
    + "         f.shipping_date, "
    + "         f.supplier_stkcd, "
    + "         f.others "
    + " from    por5mf4 a "
    + "         inner join xstpu22 b "
    + "           on a.po_order_no = b.xspo_po_order_no "
    + "           and a.backorder_flag = b.backorder_flag "
    + "         left outer join cre5mfi c "
    + "           on a.cre_accountcode = c.cre_accountcode "
    + "         left outer join "
    + "         ( "
    + "           select z.stock_group, y.shm_description "
    + "           from   stkhierachymst0 y "
    + "                  inner join stkhiertree3 z "
    + "                    on y.shm_code = z.sht_category "
    + "                    and y.shm_type = 3 "
    + "         ) d "
    + "           on b.xspo_stock_group = d.stock_group "
    + "         left outer join sys5tbl5 e "
    + "           on a.po_user_name = e.sys_tbl_code "
    + "           and e.sys_tbl_type = 'RR' "
    + "         left outer join packing_01t@scm f "
    + "           on f.po_no = a.po_order_no "
    + "           and f.po_no = '" + po_no_selected + "' "
    + "           and f.supplier_id = '" + supplier_id + "' "
    + " where   a.po_order_no = " + po_no_selected
    + " and     a.backorder_flag = ' ' "
    + " and     a.cre_accountcode = '" + supplier_id + "' ";

// sum of lines and temp packing info
sql2 =  " select  a.colour, a.ratio_desc, a.ttl_qty, nvl(b.ttl_qty, 0), nvl(b.ttl_pqty, 0), nvl(b.ttl_ctn, 0) "
      + " from    ( "
      + "           select  nvl(b.sys_description, a.xsca_colour) colour, "
      + "                   fnGetRatioLabel(c.ratio_group_code, a.xsca_ratio) ratio_desc, "
      + "                   a.xsca_total_qty ttl_qty "
      + "           from    xstcolal1 a "
      + "                   left outer join sys5tbl5 b "
      + "                     on a.xsca_colour = b.sys_tbl_code "
      + "                     and b.sys_tbl_type = 'CO' "
      + "                   inner join xstpu22 c "
      + "                     on a.xsca_po_order_no = c.xspo_po_order_no "
      + "                     and a.backorder_flag = c.backorder_flag "
      + "           where   a.xsca_po_order_no = " + po_no_selected
      + "           and     a.backorder_flag = ' ' "
      + "         ) a "
      + "         left outer join "
      + "         ( "
      + "           select  colour, sum(ttl_qty) ttl_qty, sum(ttl_pqty) ttl_pqty, sum(ttl_ctn) ttl_ctn "
      + "           from    packing_t@scm "
      + "           where   po_no = '" + po_no_selected + "' "
      + "           and     sup_id = '" + supplier_id + "' "
      + "           and     packing_date = '" + packing_date + "' "
      + "           group by colour "
      + "         ) b "
      + "           on a.colour = b.colour "
      + " order by a.colour ";

// temp packing info
sql3 =  " select  ctn_from, "
      + "         ctn_to, "
      + "         colour, "
      + "         pack_qty, "
      + "         ttl_pqty, "
      + "         ttl_qty, "
      + "         ttl_ctn "
      + " from    packing_t "
      + " where   po_no   =  '" + po_no_selected + "' "
      + " and     sup_id = '" + supplier_id + "' "
      + " and     packing_date = '" + packing_date + "' "
      + " order by ctn_from, pack_seq ";

try {

  dbPool = DBConnManager.getInstance();
  connPronto = dbPool.getConnection("pronto");
  matrix = new dbconn.MatrixDataSet();
  matrix2 = new dbconn.MatrixDataSet();
  dataProcess = new dbconn.DataProcess();

  // check differences between po lines and temp packing info
  iRet = dataProcess.RetrieveData(sql, matrix, connPronto);
  iRet2 = dataProcess.RetrieveData(sql2, matrix2, connPronto);

  connPronto.commit();

  // temp packing info
  connScm = dbPool.getConnection("intranet");
  matrix3 = new dbconn.MatrixDataSet();
  iRet3 = dataProcess.RetrieveData(sql3, matrix3, connScm);

} catch (Exception e) {
  if (connPronto != null) {
    try { connPronto.rollback(); } catch (Exception ex) {}
  }

  System.out.println("Exception in packing_made : " + e.getMessage());
  throw e;
} finally {
  if (connPronto != null) {
    dbPool.freeConnection("pronto", connPronto);
  }

  if (connScm != null) {
    dbPool.freeConnection("intranet", connScm);
  }
}

// set po details
if (iRet > 0) {
  int j = 0;
  supplier_name = matrix.getRowData(0).getData(j++);
  brand = matrix.getRowData(0).getData(j++);
  style_no = matrix.getRowData(0).getData(j++);
  buyer = matrix.getRowData(0).getData(j++);
  season = matrix.getRowData(0).getData(j++);
  trans_type = matrix.getRowData(0).getData(j++);
  delivery_date = matrix.getRowData(0).getData(j++);
  //ratio_desc = matrix.getRowData(0).getData(j++);
  shipping_date = matrix.getRowData(0).getData(j++);
  supplier_stkcd = matrix.getRowData(0).getData(j++);
  others = matrix.getRowData(0).getData(j++);

  if (shipping_date.length() == 8) { 
    shipping_date = shipping_date.substring(0, 6) + "20" + shipping_date.substring(6);
  }
}

// check and print packing quantitis
for (int i = 0; i < iRet2; i++) {
  int j = 0;
  String colour = matrix2.getRowData(i).getData(j++);
  String ratio_desc = matrix2.getRowData(i).getData(j++);
  int po_ttl_qty = Integer.parseInt(matrix2.getRowData(i).getData(j++));
  int ttl_qty = Integer.parseInt(matrix2.getRowData(i).getData(j++));
  int ttl_pqty = Integer.parseInt(matrix2.getRowData(i).getData(j++));
  int ttl_ctn = Integer.parseInt(matrix2.getRowData(i).getData(j++));

  // set po ratio labels and pack size
  String[] ratio_label = null;
  int pack_size = 0;

  colourRatioMap.put(colour, ratio_desc);
  ratio_label = ratio_desc.split(":");

  for (int k = 0; k < ratio_label.length; k++) {
    pack_size += Integer.parseInt(ratio_label[k]);
  }

  ////////////////////////////////////////////////////////////////////////////////
  // check quantity
  // 2010.12.02 Requested by Daniel(Dennis)
  // 1. Product quantity variance is acceptable up to +/- 5% per color of the proposed quantity.
  // 2. However, even if the quantity variance is within the allowance rate, the maximum acceptable 
  //    quantity variance is +/- 50 pieces per color
  // 3. If quantity variance is within +/- 10 pieces per color, and the products are packed 
  //    in bundle with correct ratio, they will be accepted irrespective of the allowance rate.
  ////////////////////////////////////////////////////////////////////////////////
  if (((double) ttl_qty > po_ttl_qty*1.1) || ((double) ttl_qty < po_ttl_qty*0.7)) {
    response.sendRedirect("./packing_error.jsp?po_no_selected=" + po_no_selected);
    return;
  }
  /*
  int diff_qty = Math.abs(ttl_qty - po_ttl_qty);

  if (diff_qty > 50) {
    response.sendRedirect("./packing_error.jsp?po_no_selected=" + po_no_selected);
    return;
  }

  if (diff_qty > 10) {
    if (((double) ttl_qty > po_ttl_qty*1.05) || ((double) ttl_qty < po_ttl_qty*0.95)) {
      response.sendRedirect("./packing_error.jsp?po_no_selected=" + po_no_selected);
      return;
    }
  }
  */
  ////////////////////////////////////////////////////////////////////////////////

  int size1_qty = ratio_label.length > 0 ? (ttl_qty*Integer.parseInt(ratio_label[0])/pack_size) : 0;
  int size2_qty = ratio_label.length > 1 ? (ttl_qty*Integer.parseInt(ratio_label[1])/pack_size) : 0;
  int size3_qty = ratio_label.length > 2 ? (ttl_qty*Integer.parseInt(ratio_label[2])/pack_size) : 0;
  int size4_qty = ratio_label.length > 3 ? (ttl_qty*Integer.parseInt(ratio_label[3])/pack_size) : 0;
  int size5_qty = ratio_label.length > 4 ? (ttl_qty*Integer.parseInt(ratio_label[4])/pack_size) : 0;
  int size6_qty = ratio_label.length > 5 ? (ttl_qty*Integer.parseInt(ratio_label[5])/pack_size) : 0;

  size1_qty_total += size1_qty;
  size2_qty_total += size2_qty;
  size3_qty_total += size3_qty;
  size4_qty_total += size4_qty;
  size5_qty_total += size5_qty;
  size6_qty_total += size6_qty;
  ttl_qty_total += ttl_qty;
  ttl_pqty_total += ttl_pqty;
  ttl_ctn_total += ttl_ctn;

  pack_lines[i] = "<td><input type='text' name='colour' value='" + colour + "' readonly size='10'></td>"
                + "<td><input type='text' name='ratio_desc' value='" + ratio_desc + "' readonly size='9'></td>"
                + "<td><input type='text' name='pcs_pack' value='" + pack_size + "' readonly size='3'></td>"
                + "<td><input type='text' name='size1_qty' value='" + size1_qty + "' readonly size='5'></td>"
                + "<td><input type='text' name='size2_qty' value='" + size2_qty + "' readonly size='5'></td>"
                + "<td><input type='text' name='size3_qty' value='" + size3_qty + "' readonly size='5'></td>"
                + "<td><input type='text' name='size4_qty' value='" + size4_qty + "' readonly size='5'></td>"
                + "<td><input type='text' name='size5_qty' value='" + size5_qty + "' readonly size='5'></td>"
                + "<td><input type='text' name='size6_qty' value='" + size6_qty + "' readonly size='5'></td>"
                + "<td colspan='2'><input type='text' name='ttl_qty' value='" + ttl_qty + "' readonly size='5'></td>"
                + "<td colspan='2'><input type='text' name='ttl_pqty' value='" + ttl_pqty + "' readonly size='5'></td>"
                + "<td colspan='2'><input type='text' name='ttl_ctn' value='" + ttl_ctn + "' readonly size='5'></td>";
}

for (int i = iRet2; i < LINE_SIZE; i++) {
  pack_lines[i] = "<td>&nbsp;</td>"
                + "<td>&nbsp;</td>"
                + "<td>&nbsp;</td>"
                + "<td>&nbsp;</td>"
                + "<td>&nbsp;</td>"
                + "<td>&nbsp;</td>"
                + "<td>&nbsp;</td>"
                + "<td>&nbsp;</td>"
                + "<td>&nbsp;</td>"
                + "<td colspan='2'>&nbsp;</td>"
                + "<td colspan='2'>&nbsp;</td>"
                + "<td colspan='2'>&nbsp;</td>";
}

// print packing detail list
for (int i = 0; i < iRet3; i++) {
  int j = 0;
  int ctn_from = Integer.parseInt(matrix3.getRowData(i).getData(j++));
  int ctn_to = Integer.parseInt(matrix3.getRowData(i).getData(j++));
  String colour = matrix3.getRowData(i).getData(j++);
  int pack_qty = Integer.parseInt(matrix3.getRowData(i).getData(j++));
  int ttl_pqty = Integer.parseInt(matrix3.getRowData(i).getData(j++));
  int ttl_qty = Integer.parseInt(matrix3.getRowData(i).getData(j++));
  int ttl_ctn = Integer.parseInt(matrix3.getRowData(i).getData(j++));

  // set po ratio labels and pack size
  int pack_size = 0;
  String ratio_desc = (String) colourRatioMap.get(colour);
  String[] ratio_label = ratio_desc.split(":");

  for (int k = 0; k < ratio_label.length; k++) {
    pack_size += Integer.parseInt(ratio_label[k]);
  }

  if (i == 0) packs_carton = pack_qty;

  int unit_qty = ttl_qty/(ctn_to - ctn_from + 1);
  int size_qty = unit_qty/pack_size;
  int c_ctn_qty = ttl_ctn > 0 ? 1 : 0;
  
  int c_size1_qty = ratio_label.length > 0 ? size_qty*Integer.parseInt(ratio_label[0]) : 0;
  int c_size2_qty = ratio_label.length > 1 ? size_qty*Integer.parseInt(ratio_label[1]) : 0;
  int c_size3_qty = ratio_label.length > 2 ? size_qty*Integer.parseInt(ratio_label[2]) : 0;
  int c_size4_qty = ratio_label.length > 3 ? size_qty*Integer.parseInt(ratio_label[3]) : 0;
  int c_size5_qty = ratio_label.length > 4 ? size_qty*Integer.parseInt(ratio_label[4]) : 0;
  int c_size6_qty = ratio_label.length > 5 ? size_qty*Integer.parseInt(ratio_label[5]) : 0;
  int c_ttl_qty = c_size1_qty + c_size2_qty + c_size3_qty + c_size4_qty + c_size5_qty + c_size6_qty;

  for (int k = ctn_from; k < ctn_to+1; k++) {
    outS += "<tr class='table_bg_bright_center'>"
          + " <td colspan='2'><input type='text' name='ctn_no' value='" + k + "' size='5' readonly></td>"
          + " <td colspan='4'><input type='text' name='c_colour' value='" + colour + "' size='10' readonly></td>"
          + " <td><input type='text' name='c_size1_qty' value='" + c_size1_qty + "' size='5' readonly></td>"
          + " <td><input type='text' name='c_size2_qty' value='" + c_size2_qty + "' size='5' readonly></td>"
          + " <td><input type='text' name='c_size3_qty' value='" + c_size3_qty + "' size='5' readonly></td>"
          + " <td><input type='text' name='c_size4_qty' value='" + c_size4_qty + "' size='5' readonly></td>"
          + " <td><input type='text' name='c_size5_qty' value='" + c_size5_qty + "' size='5' readonly></td>"
          + " <td><input type='text' name='c_size6_qty' value='" + c_size6_qty + "' size='5' readonly></td>"
          + " <td colspan='2'><input type='text' name='c_ttl_qty' value='" + c_ttl_qty + "' size='5' readonly></td>"
          + " <td colspan='2'><input type='text' name='c_ttl_pqty' value='" + pack_qty + "' size='5' readonly></td>"
          + " <td colspan='2'><input type='text' name='c_ttl_ctn' value='" + c_ctn_qty + "' size='5' readonly></td>"
          + "</tr>";
  }
}

      out.write(_jsp_string2, 0, _jsp_string2.length);
      
if (usertype.startsWith("C") || (usertype.equals("S") && usergroup.equals("F"))) {

      out.write(_jsp_string3, 0, _jsp_string3.length);
      
}

      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print(( packing_date ));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print(( po_no_selected ));
      out.write(_jsp_string6, 0, _jsp_string6.length);
      out.print(( supplier_id ));
      out.write(_jsp_string7, 0, _jsp_string7.length);
      out.print(( style_no ));
      out.write(_jsp_string8, 0, _jsp_string8.length);
      out.print(( brand ));
      out.write(_jsp_string9, 0, _jsp_string9.length);
      out.print(( buyer ));
      out.write(_jsp_string10, 0, _jsp_string10.length);
      out.print(( trans_type ));
      out.write(_jsp_string11, 0, _jsp_string11.length);
      out.print(( delivery_date ));
      out.write(_jsp_string12, 0, _jsp_string12.length);
      out.print(( season ));
      out.write(_jsp_string13, 0, _jsp_string13.length);
      out.print(( brand ));
      out.write(_jsp_string14, 0, _jsp_string14.length);
      out.print(( trans_type ));
      out.write(_jsp_string15, 0, _jsp_string15.length);
      out.print(( buyer ));
      out.write(_jsp_string16, 0, _jsp_string16.length);
      
if (usertype.startsWith("C") || (usertype.equals("S") && usergroup.equals("F"))) {

      out.write(_jsp_string17, 0, _jsp_string17.length);
      out.print(( shipping_date ));
      out.write(_jsp_string18, 0, _jsp_string18.length);
      
} else {

      out.write(_jsp_string19, 0, _jsp_string19.length);
      out.print(( shipping_date ));
      out.write(_jsp_string20, 0, _jsp_string20.length);
      
}

      out.write(_jsp_string21, 0, _jsp_string21.length);
      out.print(( supplier_name ));
      out.write(_jsp_string22, 0, _jsp_string22.length);
      out.print(( delivery_date ));
      out.write(_jsp_string23, 0, _jsp_string23.length);
      out.print(( ttl_ctn_total ));
      out.write(_jsp_string24, 0, _jsp_string24.length);
      out.print(( po_no_selected ));
      out.write(_jsp_string25, 0, _jsp_string25.length);
      out.print(( packs_carton ));
      out.write(_jsp_string26, 0, _jsp_string26.length);
      out.print(( style_no ));
      out.write(_jsp_string27, 0, _jsp_string27.length);
      out.print(( pack_lines[0] ));
      out.write(_jsp_string28, 0, _jsp_string28.length);
      out.print(( pack_lines[1] ));
      out.write(_jsp_string29, 0, _jsp_string29.length);
      out.print(( pack_lines[2] ));
      out.write(_jsp_string30, 0, _jsp_string30.length);
      out.print(( season ));
      out.write(_jsp_string31, 0, _jsp_string31.length);
      out.print(( pack_lines[3] ));
      out.write(_jsp_string32, 0, _jsp_string32.length);
      out.print(( pack_lines[4] ));
      out.write(_jsp_string33, 0, _jsp_string33.length);
      out.print(( supplier_stkcd ));
      out.write(_jsp_string34, 0, _jsp_string34.length);
      out.print(( pack_lines[5] ));
      out.write(_jsp_string35, 0, _jsp_string35.length);
      out.print(( pack_lines[6] ));
      out.write(_jsp_string36, 0, _jsp_string36.length);
      out.print(( pack_lines[7] ));
      out.write(_jsp_string37, 0, _jsp_string37.length);
      out.print(( StringUtil.formatNumber(size1_qty_total, QTY_FORMAT) ));
      out.write(_jsp_string38, 0, _jsp_string38.length);
      out.print(( StringUtil.formatNumber(size2_qty_total, QTY_FORMAT) ));
      out.write(_jsp_string38, 0, _jsp_string38.length);
      out.print(( StringUtil.formatNumber(size3_qty_total, QTY_FORMAT) ));
      out.write(_jsp_string38, 0, _jsp_string38.length);
      out.print(( StringUtil.formatNumber(size4_qty_total, QTY_FORMAT) ));
      out.write(_jsp_string38, 0, _jsp_string38.length);
      out.print(( StringUtil.formatNumber(size5_qty_total, QTY_FORMAT) ));
      out.write(_jsp_string38, 0, _jsp_string38.length);
      out.print(( StringUtil.formatNumber(size6_qty_total, QTY_FORMAT) ));
      out.write(_jsp_string39, 0, _jsp_string39.length);
      out.print(( StringUtil.formatNumber(ttl_qty_total, QTY_FORMAT) ));
      out.write(_jsp_string40, 0, _jsp_string40.length);
      out.print(( StringUtil.formatNumber(ttl_pqty_total, QTY_FORMAT) ));
      out.write(_jsp_string41, 0, _jsp_string41.length);
      out.print(( StringUtil.formatNumber(ttl_ctn_total, QTY_FORMAT) ));
      out.write(_jsp_string42, 0, _jsp_string42.length);
      out.print(( outS ));
      out.write(_jsp_string43, 0, _jsp_string43.length);
      out.print(( others ));
      out.write(_jsp_string44, 0, _jsp_string44.length);
      
out.println(CopyRightLogo());

      out.write(_jsp_string45, 0, _jsp_string45.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 5783496155892875126L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("order/packing_made.jsp"), 6873839529356195301L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("login_check.jsp"), 5313538553479869376L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("common/CommonVars.jsp"), 5055347195946766837L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("bottom_line.jsp"), 5941552803368297242L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("common/calendar/calendar.htm"), 2970746783289767368L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string5;
  private final static char []_jsp_string3;
  private final static char []_jsp_string2;
  private final static char []_jsp_string14;
  private final static char []_jsp_string20;
  private final static char []_jsp_string4;
  private final static char []_jsp_string30;
  private final static char []_jsp_string43;
  private final static char []_jsp_string15;
  private final static char []_jsp_string9;
  private final static char []_jsp_string24;
  private final static char []_jsp_string7;
  private final static char []_jsp_string10;
  private final static char []_jsp_string21;
  private final static char []_jsp_string23;
  private final static char []_jsp_string13;
  private final static char []_jsp_string36;
  private final static char []_jsp_string39;
  private final static char []_jsp_string12;
  private final static char []_jsp_string26;
  private final static char []_jsp_string11;
  private final static char []_jsp_string42;
  private final static char []_jsp_string45;
  private final static char []_jsp_string19;
  private final static char []_jsp_string33;
  private final static char []_jsp_string8;
  private final static char []_jsp_string41;
  private final static char []_jsp_string1;
  private final static char []_jsp_string34;
  private final static char []_jsp_string31;
  private final static char []_jsp_string27;
  private final static char []_jsp_string28;
  private final static char []_jsp_string38;
  private final static char []_jsp_string29;
  private final static char []_jsp_string32;
  private final static char []_jsp_string35;
  private final static char []_jsp_string25;
  private final static char []_jsp_string0;
  private final static char []_jsp_string22;
  private final static char []_jsp_string40;
  private final static char []_jsp_string18;
  private final static char []_jsp_string17;
  private final static char []_jsp_string16;
  private final static char []_jsp_string6;
  private final static char []_jsp_string44;
  private final static char []_jsp_string37;
  static {
    _jsp_string5 = "'>\n<input type='hidden' name='po_no_selected' value='".toCharArray();
    _jsp_string3 = "\n  if (!frm.shipping_date.value) {\n    alert('Shipping date must have input value and the format is dd/mm/yyyy.');\n    frm.shipping_date.focus();\n    return;\n  }\n".toCharArray();
    _jsp_string2 = "\n<html>\n<head>\n<title></title>\n<link href='/common/css/style.css' rel='stylesheet' type='text/css'>\n<script language=\"javascript\">\nfunction fnSave(frm) {\n".toCharArray();
    _jsp_string14 = "</td>\n  <th width='40%' rowspan=\"3\" class='table_bg_bright_center'>[Preview]Packing Form</th>\n  <td width='14%' class='table_header_center'>Shipping Mode</td>\n  <td width='14%' class='table_bg_bright'>".toCharArray();
    _jsp_string20 = "'>&nbsp;</td>\n".toCharArray();
    _jsp_string4 = "\n\n  if (confirm('Do you want to save packing list?')) {\n    frm.action = './packing_update.jsp';\n    frm.submit();\n  }\n}\n</script>\n</head>\n<body leftmargin=\"0\" topmargin=\"0\" marginwidth=\"0\" marginheight=\"0\">\n<table width=\"840\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n<tr><td>\n\n<table width=\"99%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\n<tr>\n  <td width=\"100%\" height=\"15\" colspan=\"2\"></td>\n</tr>\n<tr>\n  <td width=\"3%\"><img src=\"/img/title_icon.gif\"></td>\n  <td width=\"*\" class=\"left_title\">Preview of Packing Form</td>\n</tr>\n<tr>\n  <td width=\"100%\" height=\"2\" colspan=\"2\"><hr width=\"100%\"></td>\n</tr>\n<tr>\n  <td width=\"100%\" height=\"10\" colspan=\"2\"></td>\n</tr>\n</table>\n\n<table width='100%' border=\"0\" cellspacing=\"1\" cellpadding=\"2\" align=\"center\" class=\"table_bg\">\n<form name='form1' method='post'>\n<input type='hidden' name='old_packing_date' value='".toCharArray();
    _jsp_string30 = "\n</tr>\n<tr class='table_bg_bright_center'>\n  <td rowspan='2' class='table_header_center'>Season<br>Code</td>\n  <td rowspan='2' class='table_header_center'>".toCharArray();
    _jsp_string43 = "\n<tr>\n  <td colspan='2' class='table_header_center' style='background-color:#eee8aa'>Others</td>\n  <td colspan='16' class='table_bg_bright'><textarea name=\"others\" cols=\"70\" rows=\"5\">".toCharArray();
    _jsp_string15 = "</td>\n</tr>\n<tr>\n  <td class='table_header_center'>Buyer</td>\n  <td class='table_bg_bright'>".toCharArray();
    _jsp_string9 = "'>\n<input type='hidden' name='buyer' value='".toCharArray();
    _jsp_string24 = "' size='4' readonly></td>\n  <td width='3%' class='table_bg_bright'>ctns</td>\n</tr>\n<tr>\n  <td width='6%' rowspan='2' class='table_header_center'>PO #</td>\n  <td width='6%' rowspan='2' class='table_header_center'>".toCharArray();
    _jsp_string7 = "'>\n<input type='hidden' name='style_no' value='".toCharArray();
    _jsp_string10 = "'>\n<input type='hidden' name='ship_type' value='".toCharArray();
    _jsp_string21 = "\n</tr>\n<tr>\n  <td class='table_header_center'>Supplier</td>\n  <td class='table_bg_bright'>".toCharArray();
    _jsp_string23 = "</td>\n</tr>\n</table>\n\n<table width='100%' border=\"0\" cellspacing=\"1\" cellpadding=\"2\" align=\"center\" class=\"table_bg\">\n<tr>\n  <td width='76%' colspan='12' class='table_header_center'><b>PACKING FORM SUMMARY</b></td>\n  <td width='16%' colspan='4' class='table_header_center'>Tot Carton Qty</td>\n  <td width='5%' class='table_bg_bright_center'><input type='text' name='ttl_ctns' value='".toCharArray();
    _jsp_string13 = "'>\n<tr>\n  <td width='14%' class='table_header_center'>Brand</td>\n  <td width='16%' class='table_bg_bright'>".toCharArray();
    _jsp_string36 = "\n</tr>\n<tr class='table_bg_bright_center'>\n  <td class='table_header_center'>Col8</td>\n  ".toCharArray();
    _jsp_string39 = "</td>\n  <td class='table_header' align='right' width='6%'>".toCharArray();
    _jsp_string12 = "'>\n<input type='hidden' name='season_cd' value='".toCharArray();
    _jsp_string26 = "' size='5' readonly></td>\n  <td width='16%' colspan='4' class='table_bg_bright_center'>PACKS PER CARTON</td>\n</tr>\n<tr class='table_bg_bright_center'>\n  <td colspan='2' class='table_header_center'>TOT QTY</td>\n  <td colspan='2' class='table_header_center'>PACK QTY</td>\n  <td colspan='2' class='table_header_center'>CTN QTY</td>\n</tr>\n<tr class='table_bg_bright_center'>\n  <td class='table_header_center'>STY #</td>\n  <td class='table_header_center'>".toCharArray();
    _jsp_string11 = "'>\n<input type='hidden' name='delivery_date' value='".toCharArray();
    _jsp_string42 = "</td>\n  <td class='table_header'>ctns</td>\n</tr>\n<tr>\n  <td colspan='18' class='table_header_center'><b>PACKING FORM DETAIL</b></td>\n</tr>\n<tr class='table_header_center'>\n  <td colspan='2'>CTN NO.</td>\n  <td colspan='4'>COLOUR</td>\n  <td>Size 1</td>\n  <td>Size 2</td>\n  <td>Size 3</td>\n  <td>Size 4</td>\n  <td>Size 5</td>\n  <td>Size 6</td>\n  <td colspan='2'>TOT QTY</td>\n  <td colspan='2'>PACK QTY</td>\n  <td colspan='2'>CTN QTY</td>\n</tr>\n".toCharArray();
    _jsp_string45 = "\n</td></tr></table>\n</body>\n</html>\n".toCharArray();
    _jsp_string19 = "\n  <td class='table_header_center'>&nbsp;</td>\n  <td class='table_bg_bright'><input type='hidden' name='shipping_date' value='".toCharArray();
    _jsp_string33 = "\n</tr>\n<tr class='table_bg_bright_center'>\n  <td rowspan='3' class='table_header_center' style='background-color:#eee8aa'>Ref #</td>\n  <td rowspan='3' class='table_header_center'><input type='text' name='supplier_stkcd' value='".toCharArray();
    _jsp_string8 = "'>\n<input type='hidden' name='brand' value='".toCharArray();
    _jsp_string41 = "</td>\n  <td class='table_header' width='4%'>pks</td>\n  <td class='table_header' align='right'>".toCharArray();
    _jsp_string1 = "\n\n\n<Div id='popCal' style='POSITION:absolute;visibility:hidden;border:1px ridge;width:10'>\n  <iframe name=\"popFrame\" src=\"/common/calendar/popcjs.htm\" frameborder=\"0\" style=\"border:1 solid #EBF6FD\"  frameborder=\"0\" scrolling=\"no\" width=176 height=215>\n  </iframe>\n</DIV>\n<!--SCRIPT event=onclick() for=document>document.all['popCal'].style.visibility = \"hidden\";</SCRIPT-->\n<script language='javascript'>\nfunction setVisibility() {\n  document.all['popCal'].style.visibility = 'hidden';\n}\n\ndocument.onclick = setVisibility;\n</script>\n".toCharArray();
    _jsp_string34 = "' size='6' maxlength='20'></td>\n  <td class='table_header_center'>Col6</td>\n  ".toCharArray();
    _jsp_string31 = "</td>\n  <td class='table_header_center'>Col4</td>\n  ".toCharArray();
    _jsp_string27 = "</td>\n  <td width='5%' class='table_header_center'>Col1</td>\n  ".toCharArray();
    _jsp_string28 = "\n</tr>\n<tr class='table_bg_bright_center'>\n  <td rowspan='2' class='table_header_center'>Unit<br>Price</td>\n  <td rowspan='2' class='table_header_center'>&nbsp;</td>\n  <td class='table_header_center'>Col2</td>\n  ".toCharArray();
    _jsp_string38 = "</td>\n  <td class='table_header' align='right'>".toCharArray();
    _jsp_string29 = "\n</tr>\n<tr class='table_bg_bright_center'>\n  <td class='table_header_center'>Col3</td>\n  ".toCharArray();
    _jsp_string32 = "\n</tr>\n<tr class='table_bg_bright_center'>\n  <td class='table_header_center'>Col5</td>\n  ".toCharArray();
    _jsp_string35 = "\n</tr>\n<tr class='table_bg_bright_center'>\n  <td class='table_header_center'>Col7</td>\n  ".toCharArray();
    _jsp_string25 = "</td>\n  <td width='14%' colspan='2' rowspan='2' class='table_header_center'>COLOUR</td>\n  <td width='9%' rowspan='2' class='table_header_center'>RATIO</td>\n  <td width='5%' rowspan='2' class='table_header_center'>PCS PER PACK</td>\n  <td width='6%' rowspan='2' class='table_header_center'>Size 1</td>\n  <td width='6%' rowspan='2' class='table_header_center'>Size 2</td>\n  <td width='6%' rowspan='2' class='table_header_center'>Size 3</td>\n  <td width='6%' rowspan='2' class='table_header_center'>Size 4</td>\n  <td width='6%' rowspan='2' class='table_header_center'>Size 5</td>\n  <td width='6%' rowspan='2' class='table_header_center'>Size 6</td>\n  <td width='8%' colspan='2' class='table_bg_bright_center'><input type='text' name='packs_carton' value='".toCharArray();
    _jsp_string0 = "\n\n\n\n\n\n".toCharArray();
    _jsp_string22 = "</td>\n  <td class='table_header_center'>Delivery Date</td>\n  <td class='table_bg_bright'>".toCharArray();
    _jsp_string40 = "</td>\n  <td class='table_header' width='4%'>pcs</td>\n  <td class='table_header' align='right' width='6%'>".toCharArray();
    _jsp_string18 = "' readonly size='10' maxlength='10'>\n    <img src=\"/img/calendar.gif\" style=\"cursor:hand\" align=\"absmiddle\" onclick=\"javascript:popFrame.fPopCalendar(this, document.form1.shipping_date, document.all['popCal'], 'RIGHT', event);\"></td>\n".toCharArray();
    _jsp_string17 = "\n  <td class='table_header_center' style='background-color:#eee8aa'>Shipping Date</td>\n  <td class='table_bg_bright'><input type='text' name='shipping_date' value='".toCharArray();
    _jsp_string16 = "</td>\n".toCharArray();
    _jsp_string6 = "'>\n<input type='hidden' name='supplier_id' value='".toCharArray();
    _jsp_string44 = "</textarea></td>\n</tr>\n</table>\n<table width='100%' border='0' cellspacing='0' cellpadding='0' align='center'>\n<tr>\n  <td width='100%' height='10'></td>\n</tr>\n</table>\n<table width='100%' border='0' cellspacing='0' cellpadding='0' align='center'>\n<tr>\n  <td width='100%' align='center'><input type='button' value=\"Save\" onclick='fnSave(this.form)'></td></td>\n</tr>\n</form>\n</table>\n".toCharArray();
    _jsp_string37 = "\n</tr>\n<tr>\n  <td colspan='6' class='table_header_center'>Subtotal</td>\n  <td class='table_header' align='right'>".toCharArray();
  }
}
