/*
 * JSP generated by Resin-3.1.9 (built Mon, 13 Apr 2009 11:09:12 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _initpass__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html");
    try {
      
response.setHeader("Pragma","no-cache"); //HTTP 1.0
response.setDateHeader ("Expires", 0);
response.setHeader("Cache-Control","no-cache"); //HTTP 1.1

String scmid = "";
String scmnm = "";
String usertype = "";
String usergroup = "";
//String scmsubids = "";
String _adminid = "";
String _adminname = "";
String _admingroup = "";
String _apessid = "";
String _apessname = "";

try{
  scmid = (String) session.getAttribute("scmid");
  _adminid = (String) session.getAttribute("adminid");

  if( (scmid == null || scmid.length() == 0 || scmid.equals("null"))
      && (_adminid == null || _adminid.length() == 0 || _adminid.equals("null")) ) {
    response.sendRedirect("/login_first.html");
    return;
  }

  _adminname = (String) session.getAttribute("adminname");

  _apessid = (String) session.getAttribute("apessid");
  _apessname = (String) session.getAttribute("apessname");

  scmnm = (String) session.getAttribute("scmnm");

  usertype = (String) session.getAttribute("usertype");
  if (usertype == null) usertype = "";

  usergroup = (String) session.getAttribute("usergroup");
  if (usergroup == null) usergroup = "";

  //scmsubids = (String) session.getAttribute("scmsubids");
  //session.setMaxInactiveInterval(60*60);

}catch( Exception e ) {
  response.sendRedirect("/login_first.html");
  return;
}

      out.write('\n');
      
String id = request.getParameter("id");

      out.write(_jsp_string0, 0, _jsp_string0.length);
      out.print(( id ));
      out.write(_jsp_string1, 0, _jsp_string1.length);
      out.print(( id ));
      out.write(_jsp_string2, 0, _jsp_string2.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 5783496155892875126L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("initpass.jsp"), 7048575714632404679L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("login_check.jsp"), 5313538553479869376L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string2;
  private final static char []_jsp_string0;
  private final static char []_jsp_string1;
  static {
    _jsp_string2 = "</font></td>\n  </tr>\n  <tr>\n    <td width=\"22%\">\n      <p align=\"center\"><FONT SIZE=2>New Password</font></td>\n    <td width=\"24%\">\n      <p align=\"center\"><INPUT TYPE=\"password\" NAME=\"password\" SIZE=18 MAXLENGTH=10></td>\n  </tr>\n  <tr>\n    <td width=\"22%\">\n      <p align=\"center\"><FONT SIZE=2>Re-type Password</td>\n      <td width=\"24%\">\n        <p align=\"center\"><INPUT TYPE=\"password\" NAME=\"confirm\" SIZE=18 MAXLENGTH=10></td>\n    </tr>\n    <tr>\n      <td width=\"46%\" colspan=\"2\">\n        <p align=\"center\"><INPUT TYPE=BUTTON VALUE=\"Change PW\" ONCLICK=\"JavaScript:ChangePW()\">\n      </td>\n    </tr>\n  </table>\n\n</TD></TR>\n</FORM>\n</TABLE>\n<CENTER>\n\n</BODY>\n</HTML>\n".toCharArray();
    _jsp_string0 = "\n<HTML>\n<HEAD>\n<link href=\"/common/css/style.css\" rel=\"stylesheet\" type=\"text/css\">\n<SCRIPT for=\"document\" event=\"onkeypress\">\nif (window.event.keyCode==13)\n{\n        ChangePW()\n}\n</SCRIPT>\n<SCRIPT LANGUAGE=\"JavaScript\">\nfunction init()\n{\n  frmPass.password.focus();\n}\n\nfunction Reset()\n{\n  frmPass.reset();\n}\n\nfunction ChangePW()\n{\n  var check = frmPass.password.value;\n  if( check.length < 1 ) {\n    alert('New password must be at least 1 characters.');\n    return;\n  }\n  if( frmPass.password.value == frmPass.confirm.value ) {\n    frmPass.submit();\n  }else {\n    alert('New Password and retype password must be same.');\n  }\n}\n</SCRIPT>\n<meta http-equiv='Content-Type' content='text/html; charset=euc-kr'>\n</HEAD>\n<BODY ONLOAD=\"init();\" bgcolor=\"white\" TOPMARGIN=5 LEFTMARGIN=5>\n<center>\n<TABLE cellSpacing=0 cellPadding=0 width=\"433\" >\n<TBODY>\n  <TR>\n    <TD class=pgCnt vAlign=top width=1004 bgColor=#666699 height=24><IMG\n      height=18 src=\"../img/tb_st.gif\"\n      width=803 border=0></TD>\n    <TD vAlign=top width=54 height=70 rowSpan=3></TD></TR>\n  <TR>\n    <TD class=tbTxt noWrap width=689 bgColor=#666699 height=31>\n      <CENTER><B><I><FONT color=#ffffff><FONT class=tbTxt\n      face=\"Times New Roman\" size=5>Welcome to Supply Chain Management\n      System</FONT><FONT class=tbTxt face=\"Times New Roman\" size=4>\n      </FONT><FONT class=tbTxt face=\"Times New Roman\"\n      size=2></FONT></FONT></I></B></CENTER></TD></TR>\n  <TR>\n    <TD class=pgCnt vAlign=bottom noWrap width=602 height=15><IMG height=13\n      src=\"../img/tb_sb.gif\" width=804 border=0></TD></TR></TBODY>\n</TABLE>\n<TABlE width=\"679\" height=\"83\">\n<TR><TD width=\"671\" height=\"79\"></TD>\n</TABLE>\n<FORM NAME=\"frmPass\" ACTION=\"code_initpass.jsp\" METHOD=POST>\n<input type='hidden' name='id' value='".toCharArray();
    _jsp_string1 = "'>\n<TABLE WIDTH=681 height=\"288\" >\n<TR> <TD height=\"284\" width=\"673\">\n<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n  <tr>\n    <td width=\"23%\" rowspan=\"4\"><img border=\"0\" src=\"img/pass.jpg\" width=\"143\" height=\"155\"></td>\n    <td width=\"46%\" colspan=\"2\">\n      <p align=\"center\"><b><font size=\"2\" face=\"Verdana\" color=\"#0000FF\">Input your new password twice.</font></b></td>\n    <td width=\"31%\" rowspan=\"4\"></td>\n  </tr>\n  <tr>\n    <td width=\"22%\">\n      <p align=\"center\"><FONT SIZE=2>Supplier ID</font></td>\n    <td width=\"24%\">\n      <p align=\"center\"><FONT SIZE=2>".toCharArray();
  }
}
