/*
 * JSP generated by Resin-3.1.9 (built Mon, 13 Apr 2009 11:09:12 PDT)
 */

package _jsp._pnl;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.sql.*;
import dbconn.*;

public class _menu__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, "/error.jsp", session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
response.setHeader("Pragma","no-cache"); //HTTP 1.0
response.setDateHeader ("Expires", 0);
response.setHeader("Cache-Control","no-cache"); //HTTP 1.1

String _otherid = "";
String _othername = "";

try {
  _otherid = (String) session.getAttribute("otherid");

  if (_otherid == null || _otherid.length() == 0) {
    response.sendRedirect("/pnl/login_first.html");
    return;
  }

  _othername = (String) session.getAttribute("othername");
} catch( Exception e ) {
  response.sendRedirect("/pnl/login_first.html");
  return;
}

      out.write('\n');
      

      out.write(_jsp_string1, 0, _jsp_string1.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 5783496155892875126L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("pnl/menu.jsp"), -4692383981856100511L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("pnl/login_check.jsp"), 1301888329285731440L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string0;
  private final static char []_jsp_string1;
  static {
    _jsp_string0 = "\n\n\n".toCharArray();
    _jsp_string1 = "\n<html>\n<head>\n<title></title>\n<link href=\"/common/css/style.css\" rel=\"stylesheet\" type=\"text/css\">\n<style type=\"text/css\">\na:link {text-decoration: none ; color: #020468;}\na:visited {text-decoration: none ; color: #666666;}\na:active {text-decoration: underline ; color: #0770FF;}\na:hover {text-decoration: underline ; color: #0770FF;}\n</style>\n<script language=javascript src=\"/common/js/tree_win.js\"></script>\n<script language=\"javascript\">\nfunction LoadLeave()\n{\n  clearTimeout(Time_ID);\n  location.href = \"./menu.jsp\";\n}\n\nfunction delay()\n{\n  Time_ID = setTimeout(\"LoadLeave()\",( 10 * 60 * 1000 ));\n}\n</script>\n</head>\n\n<body leftmargin=\"2\" topmargin=\"10\" marginwidth=\"0\" marginheight=\"0\" bgcolor=\"#F7F7F7\" onload=\"delay()\">\n<script language=javascript>\nrootTree = genFolderRoot(\"<img src='/img/tree_base.gif' border='0'> <b>HOME</b>\", \"./delivery_status_list.jsp\");\ninsItem(rootTree, genItemIcon(\"tree_page.gif\", \"Delivery Status\", \"./delivery_status_list.jsp\"));\ninsItem(rootTree, genItemIcon(\"tree_page.gif\", \"Delivery Status(After Goods-In)\", \"./delivery_status_gi_list.jsp\"));\ninsItem(rootTree, genItemIcon(\"tree_page.gif\", \"Password Change\", \"./resetPasswdForm.jsp?fromURL=menu\"));\ninitializeDocument(rootTree);\n</script>\n</body>\n</html>".toCharArray();
  }
}
